#ifndef CROMBIE_REGFILE_H
#define CROMBIE_REGFILE_H

#include <string>
#include <vector>
#include "TObject.h"
#include "TFile.h"
#include "TTree.h"
#include "lazytf.h"
#include "genjet.h"
#include "pfvecs.h"
#include "regression.h"
#include "TVector2.h"

class regfile {

 public:
  regfile(const char* outfile_name, const char* name = "events");
  ~regfile() { write(t); f->Close(); }

  Float_t Jet_btagCMVA;
  Float_t Jet_btagDeepB;
  Float_t Jet_btagDeepC;
  Float_t Jet_chEmEF;
  Float_t Jet_chHEF;
  Float_t Jet_e;
  Float_t Jet_eta;
  Float_t Jet_mass;
  Float_t Jet_mcEta;
  Float_t Jet_mcFlavour;
  Float_t Jet_mcM;
  Float_t Jet_mcPhi;
  Float_t Jet_mcPt;
  Float_t Jet_met_dPhi;
  Float_t Jet_mt;
  Float_t Jet_neEmEF;
  Float_t Jet_neHEF;
  UShort_t Jet_numberOfDaughters;
  Float_t Jet_pf_0_deta;
  Float_t Jet_pf_0_dphi;
  Float_t Jet_pf_0_dxy;
  Float_t Jet_pf_0_dz;
  Bool_t Jet_pf_0_is_chhadron;
  Bool_t Jet_pf_0_is_ele;
  Bool_t Jet_pf_0_is_muon;
  Bool_t Jet_pf_0_is_nhadron;
  Bool_t Jet_pf_0_is_photon;
  Float_t Jet_pf_0_ptfrac;
  Float_t Jet_pf_0_puppiwt;
  Char_t Jet_pf_0_q;
  Float_t Jet_pf_0_transformed_px;
  Float_t Jet_pf_0_transformed_py;
  Float_t Jet_pf_0_transformed_pz;
  Float_t Jet_pf_10_deta;
  Float_t Jet_pf_10_dphi;
  Float_t Jet_pf_10_dxy;
  Float_t Jet_pf_10_dz;
  Bool_t Jet_pf_10_is_chhadron;
  Bool_t Jet_pf_10_is_ele;
  Bool_t Jet_pf_10_is_muon;
  Bool_t Jet_pf_10_is_nhadron;
  Bool_t Jet_pf_10_is_photon;
  Float_t Jet_pf_10_ptfrac;
  Float_t Jet_pf_10_puppiwt;
  Char_t Jet_pf_10_q;
  Float_t Jet_pf_10_transformed_px;
  Float_t Jet_pf_10_transformed_py;
  Float_t Jet_pf_10_transformed_pz;
  Float_t Jet_pf_11_deta;
  Float_t Jet_pf_11_dphi;
  Float_t Jet_pf_11_dxy;
  Float_t Jet_pf_11_dz;
  Bool_t Jet_pf_11_is_chhadron;
  Bool_t Jet_pf_11_is_ele;
  Bool_t Jet_pf_11_is_muon;
  Bool_t Jet_pf_11_is_nhadron;
  Bool_t Jet_pf_11_is_photon;
  Float_t Jet_pf_11_ptfrac;
  Float_t Jet_pf_11_puppiwt;
  Char_t Jet_pf_11_q;
  Float_t Jet_pf_11_transformed_px;
  Float_t Jet_pf_11_transformed_py;
  Float_t Jet_pf_11_transformed_pz;
  Float_t Jet_pf_12_deta;
  Float_t Jet_pf_12_dphi;
  Float_t Jet_pf_12_dxy;
  Float_t Jet_pf_12_dz;
  Bool_t Jet_pf_12_is_chhadron;
  Bool_t Jet_pf_12_is_ele;
  Bool_t Jet_pf_12_is_muon;
  Bool_t Jet_pf_12_is_nhadron;
  Bool_t Jet_pf_12_is_photon;
  Float_t Jet_pf_12_ptfrac;
  Float_t Jet_pf_12_puppiwt;
  Char_t Jet_pf_12_q;
  Float_t Jet_pf_12_transformed_px;
  Float_t Jet_pf_12_transformed_py;
  Float_t Jet_pf_12_transformed_pz;
  Float_t Jet_pf_13_deta;
  Float_t Jet_pf_13_dphi;
  Float_t Jet_pf_13_dxy;
  Float_t Jet_pf_13_dz;
  Bool_t Jet_pf_13_is_chhadron;
  Bool_t Jet_pf_13_is_ele;
  Bool_t Jet_pf_13_is_muon;
  Bool_t Jet_pf_13_is_nhadron;
  Bool_t Jet_pf_13_is_photon;
  Float_t Jet_pf_13_ptfrac;
  Float_t Jet_pf_13_puppiwt;
  Char_t Jet_pf_13_q;
  Float_t Jet_pf_13_transformed_px;
  Float_t Jet_pf_13_transformed_py;
  Float_t Jet_pf_13_transformed_pz;
  Float_t Jet_pf_14_deta;
  Float_t Jet_pf_14_dphi;
  Float_t Jet_pf_14_dxy;
  Float_t Jet_pf_14_dz;
  Bool_t Jet_pf_14_is_chhadron;
  Bool_t Jet_pf_14_is_ele;
  Bool_t Jet_pf_14_is_muon;
  Bool_t Jet_pf_14_is_nhadron;
  Bool_t Jet_pf_14_is_photon;
  Float_t Jet_pf_14_ptfrac;
  Float_t Jet_pf_14_puppiwt;
  Char_t Jet_pf_14_q;
  Float_t Jet_pf_14_transformed_px;
  Float_t Jet_pf_14_transformed_py;
  Float_t Jet_pf_14_transformed_pz;
  Float_t Jet_pf_15_deta;
  Float_t Jet_pf_15_dphi;
  Float_t Jet_pf_15_dxy;
  Float_t Jet_pf_15_dz;
  Bool_t Jet_pf_15_is_chhadron;
  Bool_t Jet_pf_15_is_ele;
  Bool_t Jet_pf_15_is_muon;
  Bool_t Jet_pf_15_is_nhadron;
  Bool_t Jet_pf_15_is_photon;
  Float_t Jet_pf_15_ptfrac;
  Float_t Jet_pf_15_puppiwt;
  Char_t Jet_pf_15_q;
  Float_t Jet_pf_15_transformed_px;
  Float_t Jet_pf_15_transformed_py;
  Float_t Jet_pf_15_transformed_pz;
  Float_t Jet_pf_16_deta;
  Float_t Jet_pf_16_dphi;
  Float_t Jet_pf_16_dxy;
  Float_t Jet_pf_16_dz;
  Bool_t Jet_pf_16_is_chhadron;
  Bool_t Jet_pf_16_is_ele;
  Bool_t Jet_pf_16_is_muon;
  Bool_t Jet_pf_16_is_nhadron;
  Bool_t Jet_pf_16_is_photon;
  Float_t Jet_pf_16_ptfrac;
  Float_t Jet_pf_16_puppiwt;
  Char_t Jet_pf_16_q;
  Float_t Jet_pf_16_transformed_px;
  Float_t Jet_pf_16_transformed_py;
  Float_t Jet_pf_16_transformed_pz;
  Float_t Jet_pf_17_deta;
  Float_t Jet_pf_17_dphi;
  Float_t Jet_pf_17_dxy;
  Float_t Jet_pf_17_dz;
  Bool_t Jet_pf_17_is_chhadron;
  Bool_t Jet_pf_17_is_ele;
  Bool_t Jet_pf_17_is_muon;
  Bool_t Jet_pf_17_is_nhadron;
  Bool_t Jet_pf_17_is_photon;
  Float_t Jet_pf_17_ptfrac;
  Float_t Jet_pf_17_puppiwt;
  Char_t Jet_pf_17_q;
  Float_t Jet_pf_17_transformed_px;
  Float_t Jet_pf_17_transformed_py;
  Float_t Jet_pf_17_transformed_pz;
  Float_t Jet_pf_18_deta;
  Float_t Jet_pf_18_dphi;
  Float_t Jet_pf_18_dxy;
  Float_t Jet_pf_18_dz;
  Bool_t Jet_pf_18_is_chhadron;
  Bool_t Jet_pf_18_is_ele;
  Bool_t Jet_pf_18_is_muon;
  Bool_t Jet_pf_18_is_nhadron;
  Bool_t Jet_pf_18_is_photon;
  Float_t Jet_pf_18_ptfrac;
  Float_t Jet_pf_18_puppiwt;
  Char_t Jet_pf_18_q;
  Float_t Jet_pf_18_transformed_px;
  Float_t Jet_pf_18_transformed_py;
  Float_t Jet_pf_18_transformed_pz;
  Float_t Jet_pf_19_deta;
  Float_t Jet_pf_19_dphi;
  Float_t Jet_pf_19_dxy;
  Float_t Jet_pf_19_dz;
  Bool_t Jet_pf_19_is_chhadron;
  Bool_t Jet_pf_19_is_ele;
  Bool_t Jet_pf_19_is_muon;
  Bool_t Jet_pf_19_is_nhadron;
  Bool_t Jet_pf_19_is_photon;
  Float_t Jet_pf_19_ptfrac;
  Float_t Jet_pf_19_puppiwt;
  Char_t Jet_pf_19_q;
  Float_t Jet_pf_19_transformed_px;
  Float_t Jet_pf_19_transformed_py;
  Float_t Jet_pf_19_transformed_pz;
  Float_t Jet_pf_1_deta;
  Float_t Jet_pf_1_dphi;
  Float_t Jet_pf_1_dxy;
  Float_t Jet_pf_1_dz;
  Bool_t Jet_pf_1_is_chhadron;
  Bool_t Jet_pf_1_is_ele;
  Bool_t Jet_pf_1_is_muon;
  Bool_t Jet_pf_1_is_nhadron;
  Bool_t Jet_pf_1_is_photon;
  Float_t Jet_pf_1_ptfrac;
  Float_t Jet_pf_1_puppiwt;
  Char_t Jet_pf_1_q;
  Float_t Jet_pf_1_transformed_px;
  Float_t Jet_pf_1_transformed_py;
  Float_t Jet_pf_1_transformed_pz;
  Float_t Jet_pf_2_deta;
  Float_t Jet_pf_2_dphi;
  Float_t Jet_pf_2_dxy;
  Float_t Jet_pf_2_dz;
  Bool_t Jet_pf_2_is_chhadron;
  Bool_t Jet_pf_2_is_ele;
  Bool_t Jet_pf_2_is_muon;
  Bool_t Jet_pf_2_is_nhadron;
  Bool_t Jet_pf_2_is_photon;
  Float_t Jet_pf_2_ptfrac;
  Float_t Jet_pf_2_puppiwt;
  Char_t Jet_pf_2_q;
  Float_t Jet_pf_2_transformed_px;
  Float_t Jet_pf_2_transformed_py;
  Float_t Jet_pf_2_transformed_pz;
  Float_t Jet_pf_3_deta;
  Float_t Jet_pf_3_dphi;
  Float_t Jet_pf_3_dxy;
  Float_t Jet_pf_3_dz;
  Bool_t Jet_pf_3_is_chhadron;
  Bool_t Jet_pf_3_is_ele;
  Bool_t Jet_pf_3_is_muon;
  Bool_t Jet_pf_3_is_nhadron;
  Bool_t Jet_pf_3_is_photon;
  Float_t Jet_pf_3_ptfrac;
  Float_t Jet_pf_3_puppiwt;
  Char_t Jet_pf_3_q;
  Float_t Jet_pf_3_transformed_px;
  Float_t Jet_pf_3_transformed_py;
  Float_t Jet_pf_3_transformed_pz;
  Float_t Jet_pf_4_deta;
  Float_t Jet_pf_4_dphi;
  Float_t Jet_pf_4_dxy;
  Float_t Jet_pf_4_dz;
  Bool_t Jet_pf_4_is_chhadron;
  Bool_t Jet_pf_4_is_ele;
  Bool_t Jet_pf_4_is_muon;
  Bool_t Jet_pf_4_is_nhadron;
  Bool_t Jet_pf_4_is_photon;
  Float_t Jet_pf_4_ptfrac;
  Float_t Jet_pf_4_puppiwt;
  Char_t Jet_pf_4_q;
  Float_t Jet_pf_4_transformed_px;
  Float_t Jet_pf_4_transformed_py;
  Float_t Jet_pf_4_transformed_pz;
  Float_t Jet_pf_5_deta;
  Float_t Jet_pf_5_dphi;
  Float_t Jet_pf_5_dxy;
  Float_t Jet_pf_5_dz;
  Bool_t Jet_pf_5_is_chhadron;
  Bool_t Jet_pf_5_is_ele;
  Bool_t Jet_pf_5_is_muon;
  Bool_t Jet_pf_5_is_nhadron;
  Bool_t Jet_pf_5_is_photon;
  Float_t Jet_pf_5_ptfrac;
  Float_t Jet_pf_5_puppiwt;
  Char_t Jet_pf_5_q;
  Float_t Jet_pf_5_transformed_px;
  Float_t Jet_pf_5_transformed_py;
  Float_t Jet_pf_5_transformed_pz;
  Float_t Jet_pf_6_deta;
  Float_t Jet_pf_6_dphi;
  Float_t Jet_pf_6_dxy;
  Float_t Jet_pf_6_dz;
  Bool_t Jet_pf_6_is_chhadron;
  Bool_t Jet_pf_6_is_ele;
  Bool_t Jet_pf_6_is_muon;
  Bool_t Jet_pf_6_is_nhadron;
  Bool_t Jet_pf_6_is_photon;
  Float_t Jet_pf_6_ptfrac;
  Float_t Jet_pf_6_puppiwt;
  Char_t Jet_pf_6_q;
  Float_t Jet_pf_6_transformed_px;
  Float_t Jet_pf_6_transformed_py;
  Float_t Jet_pf_6_transformed_pz;
  Float_t Jet_pf_7_deta;
  Float_t Jet_pf_7_dphi;
  Float_t Jet_pf_7_dxy;
  Float_t Jet_pf_7_dz;
  Bool_t Jet_pf_7_is_chhadron;
  Bool_t Jet_pf_7_is_ele;
  Bool_t Jet_pf_7_is_muon;
  Bool_t Jet_pf_7_is_nhadron;
  Bool_t Jet_pf_7_is_photon;
  Float_t Jet_pf_7_ptfrac;
  Float_t Jet_pf_7_puppiwt;
  Char_t Jet_pf_7_q;
  Float_t Jet_pf_7_transformed_px;
  Float_t Jet_pf_7_transformed_py;
  Float_t Jet_pf_7_transformed_pz;
  Float_t Jet_pf_8_deta;
  Float_t Jet_pf_8_dphi;
  Float_t Jet_pf_8_dxy;
  Float_t Jet_pf_8_dz;
  Bool_t Jet_pf_8_is_chhadron;
  Bool_t Jet_pf_8_is_ele;
  Bool_t Jet_pf_8_is_muon;
  Bool_t Jet_pf_8_is_nhadron;
  Bool_t Jet_pf_8_is_photon;
  Float_t Jet_pf_8_ptfrac;
  Float_t Jet_pf_8_puppiwt;
  Char_t Jet_pf_8_q;
  Float_t Jet_pf_8_transformed_px;
  Float_t Jet_pf_8_transformed_py;
  Float_t Jet_pf_8_transformed_pz;
  Float_t Jet_pf_9_deta;
  Float_t Jet_pf_9_dphi;
  Float_t Jet_pf_9_dxy;
  Float_t Jet_pf_9_dz;
  Bool_t Jet_pf_9_is_chhadron;
  Bool_t Jet_pf_9_is_ele;
  Bool_t Jet_pf_9_is_muon;
  Bool_t Jet_pf_9_is_nhadron;
  Bool_t Jet_pf_9_is_photon;
  Float_t Jet_pf_9_ptfrac;
  Float_t Jet_pf_9_puppiwt;
  Char_t Jet_pf_9_q;
  Float_t Jet_pf_9_transformed_px;
  Float_t Jet_pf_9_transformed_py;
  Float_t Jet_pf_9_transformed_pz;
  Float_t Jet_phi;
  Float_t Jet_pt;
  Float_t Jet_puId;
  Float_t Jet_raw;
  ULong64_t event;
  Float_t genWeight;
  ULong64_t luminosityBlock;
  Float_t met_phi;
  Float_t met_pt;
  Float_t nPVs;
  Float_t nPVs_good;
  TVector3 pv;
  Float_t rho;
  UInt_t run;

  void reset(const panda::Event& e);
  void fill();
  void write(TObject* obj) { f->WriteTObject(obj, obj->GetName()); }
  
  enum class jet {
    Jet
  };
  template <typename G> void set_jet(const jet base, const panda::Jet& jet, const gennujet::GenNuVec& withnu, const G gen);

 private:
  TFile* f;
  TTree* t;

};

regfile::regfile(const char* outfile_name, const char* name)
: f {new TFile(outfile_name, "CREATE", "", 1)},
  t {new TTree(name, name)}
{
  t->Branch("Jet_btagCMVA", &Jet_btagCMVA, "Jet_btagCMVA/F");
  t->Branch("Jet_btagDeepB", &Jet_btagDeepB, "Jet_btagDeepB/F");
  t->Branch("Jet_btagDeepC", &Jet_btagDeepC, "Jet_btagDeepC/F");
  t->Branch("Jet_chEmEF", &Jet_chEmEF, "Jet_chEmEF/F");
  t->Branch("Jet_chHEF", &Jet_chHEF, "Jet_chHEF/F");
  t->Branch("Jet_e", &Jet_e, "Jet_e/F");
  t->Branch("Jet_eta", &Jet_eta, "Jet_eta/F");
  t->Branch("Jet_mass", &Jet_mass, "Jet_mass/F");
  t->Branch("Jet_mcEta", &Jet_mcEta, "Jet_mcEta/F");
  t->Branch("Jet_mcFlavour", &Jet_mcFlavour, "Jet_mcFlavour/F");
  t->Branch("Jet_mcM", &Jet_mcM, "Jet_mcM/F");
  t->Branch("Jet_mcPhi", &Jet_mcPhi, "Jet_mcPhi/F");
  t->Branch("Jet_mcPt", &Jet_mcPt, "Jet_mcPt/F");
  t->Branch("Jet_met_dPhi", &Jet_met_dPhi, "Jet_met_dPhi/F");
  t->Branch("Jet_mt", &Jet_mt, "Jet_mt/F");
  t->Branch("Jet_neEmEF", &Jet_neEmEF, "Jet_neEmEF/F");
  t->Branch("Jet_neHEF", &Jet_neHEF, "Jet_neHEF/F");
  t->Branch("Jet_numberOfDaughters", &Jet_numberOfDaughters, "Jet_numberOfDaughters/s");
  t->Branch("Jet_pf_0_deta", &Jet_pf_0_deta, "Jet_pf_0_deta/F");
  t->Branch("Jet_pf_0_dphi", &Jet_pf_0_dphi, "Jet_pf_0_dphi/F");
  t->Branch("Jet_pf_0_dxy", &Jet_pf_0_dxy, "Jet_pf_0_dxy/F");
  t->Branch("Jet_pf_0_dz", &Jet_pf_0_dz, "Jet_pf_0_dz/F");
  t->Branch("Jet_pf_0_is_chhadron", &Jet_pf_0_is_chhadron, "Jet_pf_0_is_chhadron/O");
  t->Branch("Jet_pf_0_is_ele", &Jet_pf_0_is_ele, "Jet_pf_0_is_ele/O");
  t->Branch("Jet_pf_0_is_muon", &Jet_pf_0_is_muon, "Jet_pf_0_is_muon/O");
  t->Branch("Jet_pf_0_is_nhadron", &Jet_pf_0_is_nhadron, "Jet_pf_0_is_nhadron/O");
  t->Branch("Jet_pf_0_is_photon", &Jet_pf_0_is_photon, "Jet_pf_0_is_photon/O");
  t->Branch("Jet_pf_0_ptfrac", &Jet_pf_0_ptfrac, "Jet_pf_0_ptfrac/F");
  t->Branch("Jet_pf_0_puppiwt", &Jet_pf_0_puppiwt, "Jet_pf_0_puppiwt/F");
  t->Branch("Jet_pf_0_q", &Jet_pf_0_q, "Jet_pf_0_q/B");
  t->Branch("Jet_pf_0_transformed_px", &Jet_pf_0_transformed_px, "Jet_pf_0_transformed_px/F");
  t->Branch("Jet_pf_0_transformed_py", &Jet_pf_0_transformed_py, "Jet_pf_0_transformed_py/F");
  t->Branch("Jet_pf_0_transformed_pz", &Jet_pf_0_transformed_pz, "Jet_pf_0_transformed_pz/F");
  t->Branch("Jet_pf_10_deta", &Jet_pf_10_deta, "Jet_pf_10_deta/F");
  t->Branch("Jet_pf_10_dphi", &Jet_pf_10_dphi, "Jet_pf_10_dphi/F");
  t->Branch("Jet_pf_10_dxy", &Jet_pf_10_dxy, "Jet_pf_10_dxy/F");
  t->Branch("Jet_pf_10_dz", &Jet_pf_10_dz, "Jet_pf_10_dz/F");
  t->Branch("Jet_pf_10_is_chhadron", &Jet_pf_10_is_chhadron, "Jet_pf_10_is_chhadron/O");
  t->Branch("Jet_pf_10_is_ele", &Jet_pf_10_is_ele, "Jet_pf_10_is_ele/O");
  t->Branch("Jet_pf_10_is_muon", &Jet_pf_10_is_muon, "Jet_pf_10_is_muon/O");
  t->Branch("Jet_pf_10_is_nhadron", &Jet_pf_10_is_nhadron, "Jet_pf_10_is_nhadron/O");
  t->Branch("Jet_pf_10_is_photon", &Jet_pf_10_is_photon, "Jet_pf_10_is_photon/O");
  t->Branch("Jet_pf_10_ptfrac", &Jet_pf_10_ptfrac, "Jet_pf_10_ptfrac/F");
  t->Branch("Jet_pf_10_puppiwt", &Jet_pf_10_puppiwt, "Jet_pf_10_puppiwt/F");
  t->Branch("Jet_pf_10_q", &Jet_pf_10_q, "Jet_pf_10_q/B");
  t->Branch("Jet_pf_10_transformed_px", &Jet_pf_10_transformed_px, "Jet_pf_10_transformed_px/F");
  t->Branch("Jet_pf_10_transformed_py", &Jet_pf_10_transformed_py, "Jet_pf_10_transformed_py/F");
  t->Branch("Jet_pf_10_transformed_pz", &Jet_pf_10_transformed_pz, "Jet_pf_10_transformed_pz/F");
  t->Branch("Jet_pf_11_deta", &Jet_pf_11_deta, "Jet_pf_11_deta/F");
  t->Branch("Jet_pf_11_dphi", &Jet_pf_11_dphi, "Jet_pf_11_dphi/F");
  t->Branch("Jet_pf_11_dxy", &Jet_pf_11_dxy, "Jet_pf_11_dxy/F");
  t->Branch("Jet_pf_11_dz", &Jet_pf_11_dz, "Jet_pf_11_dz/F");
  t->Branch("Jet_pf_11_is_chhadron", &Jet_pf_11_is_chhadron, "Jet_pf_11_is_chhadron/O");
  t->Branch("Jet_pf_11_is_ele", &Jet_pf_11_is_ele, "Jet_pf_11_is_ele/O");
  t->Branch("Jet_pf_11_is_muon", &Jet_pf_11_is_muon, "Jet_pf_11_is_muon/O");
  t->Branch("Jet_pf_11_is_nhadron", &Jet_pf_11_is_nhadron, "Jet_pf_11_is_nhadron/O");
  t->Branch("Jet_pf_11_is_photon", &Jet_pf_11_is_photon, "Jet_pf_11_is_photon/O");
  t->Branch("Jet_pf_11_ptfrac", &Jet_pf_11_ptfrac, "Jet_pf_11_ptfrac/F");
  t->Branch("Jet_pf_11_puppiwt", &Jet_pf_11_puppiwt, "Jet_pf_11_puppiwt/F");
  t->Branch("Jet_pf_11_q", &Jet_pf_11_q, "Jet_pf_11_q/B");
  t->Branch("Jet_pf_11_transformed_px", &Jet_pf_11_transformed_px, "Jet_pf_11_transformed_px/F");
  t->Branch("Jet_pf_11_transformed_py", &Jet_pf_11_transformed_py, "Jet_pf_11_transformed_py/F");
  t->Branch("Jet_pf_11_transformed_pz", &Jet_pf_11_transformed_pz, "Jet_pf_11_transformed_pz/F");
  t->Branch("Jet_pf_12_deta", &Jet_pf_12_deta, "Jet_pf_12_deta/F");
  t->Branch("Jet_pf_12_dphi", &Jet_pf_12_dphi, "Jet_pf_12_dphi/F");
  t->Branch("Jet_pf_12_dxy", &Jet_pf_12_dxy, "Jet_pf_12_dxy/F");
  t->Branch("Jet_pf_12_dz", &Jet_pf_12_dz, "Jet_pf_12_dz/F");
  t->Branch("Jet_pf_12_is_chhadron", &Jet_pf_12_is_chhadron, "Jet_pf_12_is_chhadron/O");
  t->Branch("Jet_pf_12_is_ele", &Jet_pf_12_is_ele, "Jet_pf_12_is_ele/O");
  t->Branch("Jet_pf_12_is_muon", &Jet_pf_12_is_muon, "Jet_pf_12_is_muon/O");
  t->Branch("Jet_pf_12_is_nhadron", &Jet_pf_12_is_nhadron, "Jet_pf_12_is_nhadron/O");
  t->Branch("Jet_pf_12_is_photon", &Jet_pf_12_is_photon, "Jet_pf_12_is_photon/O");
  t->Branch("Jet_pf_12_ptfrac", &Jet_pf_12_ptfrac, "Jet_pf_12_ptfrac/F");
  t->Branch("Jet_pf_12_puppiwt", &Jet_pf_12_puppiwt, "Jet_pf_12_puppiwt/F");
  t->Branch("Jet_pf_12_q", &Jet_pf_12_q, "Jet_pf_12_q/B");
  t->Branch("Jet_pf_12_transformed_px", &Jet_pf_12_transformed_px, "Jet_pf_12_transformed_px/F");
  t->Branch("Jet_pf_12_transformed_py", &Jet_pf_12_transformed_py, "Jet_pf_12_transformed_py/F");
  t->Branch("Jet_pf_12_transformed_pz", &Jet_pf_12_transformed_pz, "Jet_pf_12_transformed_pz/F");
  t->Branch("Jet_pf_13_deta", &Jet_pf_13_deta, "Jet_pf_13_deta/F");
  t->Branch("Jet_pf_13_dphi", &Jet_pf_13_dphi, "Jet_pf_13_dphi/F");
  t->Branch("Jet_pf_13_dxy", &Jet_pf_13_dxy, "Jet_pf_13_dxy/F");
  t->Branch("Jet_pf_13_dz", &Jet_pf_13_dz, "Jet_pf_13_dz/F");
  t->Branch("Jet_pf_13_is_chhadron", &Jet_pf_13_is_chhadron, "Jet_pf_13_is_chhadron/O");
  t->Branch("Jet_pf_13_is_ele", &Jet_pf_13_is_ele, "Jet_pf_13_is_ele/O");
  t->Branch("Jet_pf_13_is_muon", &Jet_pf_13_is_muon, "Jet_pf_13_is_muon/O");
  t->Branch("Jet_pf_13_is_nhadron", &Jet_pf_13_is_nhadron, "Jet_pf_13_is_nhadron/O");
  t->Branch("Jet_pf_13_is_photon", &Jet_pf_13_is_photon, "Jet_pf_13_is_photon/O");
  t->Branch("Jet_pf_13_ptfrac", &Jet_pf_13_ptfrac, "Jet_pf_13_ptfrac/F");
  t->Branch("Jet_pf_13_puppiwt", &Jet_pf_13_puppiwt, "Jet_pf_13_puppiwt/F");
  t->Branch("Jet_pf_13_q", &Jet_pf_13_q, "Jet_pf_13_q/B");
  t->Branch("Jet_pf_13_transformed_px", &Jet_pf_13_transformed_px, "Jet_pf_13_transformed_px/F");
  t->Branch("Jet_pf_13_transformed_py", &Jet_pf_13_transformed_py, "Jet_pf_13_transformed_py/F");
  t->Branch("Jet_pf_13_transformed_pz", &Jet_pf_13_transformed_pz, "Jet_pf_13_transformed_pz/F");
  t->Branch("Jet_pf_14_deta", &Jet_pf_14_deta, "Jet_pf_14_deta/F");
  t->Branch("Jet_pf_14_dphi", &Jet_pf_14_dphi, "Jet_pf_14_dphi/F");
  t->Branch("Jet_pf_14_dxy", &Jet_pf_14_dxy, "Jet_pf_14_dxy/F");
  t->Branch("Jet_pf_14_dz", &Jet_pf_14_dz, "Jet_pf_14_dz/F");
  t->Branch("Jet_pf_14_is_chhadron", &Jet_pf_14_is_chhadron, "Jet_pf_14_is_chhadron/O");
  t->Branch("Jet_pf_14_is_ele", &Jet_pf_14_is_ele, "Jet_pf_14_is_ele/O");
  t->Branch("Jet_pf_14_is_muon", &Jet_pf_14_is_muon, "Jet_pf_14_is_muon/O");
  t->Branch("Jet_pf_14_is_nhadron", &Jet_pf_14_is_nhadron, "Jet_pf_14_is_nhadron/O");
  t->Branch("Jet_pf_14_is_photon", &Jet_pf_14_is_photon, "Jet_pf_14_is_photon/O");
  t->Branch("Jet_pf_14_ptfrac", &Jet_pf_14_ptfrac, "Jet_pf_14_ptfrac/F");
  t->Branch("Jet_pf_14_puppiwt", &Jet_pf_14_puppiwt, "Jet_pf_14_puppiwt/F");
  t->Branch("Jet_pf_14_q", &Jet_pf_14_q, "Jet_pf_14_q/B");
  t->Branch("Jet_pf_14_transformed_px", &Jet_pf_14_transformed_px, "Jet_pf_14_transformed_px/F");
  t->Branch("Jet_pf_14_transformed_py", &Jet_pf_14_transformed_py, "Jet_pf_14_transformed_py/F");
  t->Branch("Jet_pf_14_transformed_pz", &Jet_pf_14_transformed_pz, "Jet_pf_14_transformed_pz/F");
  t->Branch("Jet_pf_15_deta", &Jet_pf_15_deta, "Jet_pf_15_deta/F");
  t->Branch("Jet_pf_15_dphi", &Jet_pf_15_dphi, "Jet_pf_15_dphi/F");
  t->Branch("Jet_pf_15_dxy", &Jet_pf_15_dxy, "Jet_pf_15_dxy/F");
  t->Branch("Jet_pf_15_dz", &Jet_pf_15_dz, "Jet_pf_15_dz/F");
  t->Branch("Jet_pf_15_is_chhadron", &Jet_pf_15_is_chhadron, "Jet_pf_15_is_chhadron/O");
  t->Branch("Jet_pf_15_is_ele", &Jet_pf_15_is_ele, "Jet_pf_15_is_ele/O");
  t->Branch("Jet_pf_15_is_muon", &Jet_pf_15_is_muon, "Jet_pf_15_is_muon/O");
  t->Branch("Jet_pf_15_is_nhadron", &Jet_pf_15_is_nhadron, "Jet_pf_15_is_nhadron/O");
  t->Branch("Jet_pf_15_is_photon", &Jet_pf_15_is_photon, "Jet_pf_15_is_photon/O");
  t->Branch("Jet_pf_15_ptfrac", &Jet_pf_15_ptfrac, "Jet_pf_15_ptfrac/F");
  t->Branch("Jet_pf_15_puppiwt", &Jet_pf_15_puppiwt, "Jet_pf_15_puppiwt/F");
  t->Branch("Jet_pf_15_q", &Jet_pf_15_q, "Jet_pf_15_q/B");
  t->Branch("Jet_pf_15_transformed_px", &Jet_pf_15_transformed_px, "Jet_pf_15_transformed_px/F");
  t->Branch("Jet_pf_15_transformed_py", &Jet_pf_15_transformed_py, "Jet_pf_15_transformed_py/F");
  t->Branch("Jet_pf_15_transformed_pz", &Jet_pf_15_transformed_pz, "Jet_pf_15_transformed_pz/F");
  t->Branch("Jet_pf_16_deta", &Jet_pf_16_deta, "Jet_pf_16_deta/F");
  t->Branch("Jet_pf_16_dphi", &Jet_pf_16_dphi, "Jet_pf_16_dphi/F");
  t->Branch("Jet_pf_16_dxy", &Jet_pf_16_dxy, "Jet_pf_16_dxy/F");
  t->Branch("Jet_pf_16_dz", &Jet_pf_16_dz, "Jet_pf_16_dz/F");
  t->Branch("Jet_pf_16_is_chhadron", &Jet_pf_16_is_chhadron, "Jet_pf_16_is_chhadron/O");
  t->Branch("Jet_pf_16_is_ele", &Jet_pf_16_is_ele, "Jet_pf_16_is_ele/O");
  t->Branch("Jet_pf_16_is_muon", &Jet_pf_16_is_muon, "Jet_pf_16_is_muon/O");
  t->Branch("Jet_pf_16_is_nhadron", &Jet_pf_16_is_nhadron, "Jet_pf_16_is_nhadron/O");
  t->Branch("Jet_pf_16_is_photon", &Jet_pf_16_is_photon, "Jet_pf_16_is_photon/O");
  t->Branch("Jet_pf_16_ptfrac", &Jet_pf_16_ptfrac, "Jet_pf_16_ptfrac/F");
  t->Branch("Jet_pf_16_puppiwt", &Jet_pf_16_puppiwt, "Jet_pf_16_puppiwt/F");
  t->Branch("Jet_pf_16_q", &Jet_pf_16_q, "Jet_pf_16_q/B");
  t->Branch("Jet_pf_16_transformed_px", &Jet_pf_16_transformed_px, "Jet_pf_16_transformed_px/F");
  t->Branch("Jet_pf_16_transformed_py", &Jet_pf_16_transformed_py, "Jet_pf_16_transformed_py/F");
  t->Branch("Jet_pf_16_transformed_pz", &Jet_pf_16_transformed_pz, "Jet_pf_16_transformed_pz/F");
  t->Branch("Jet_pf_17_deta", &Jet_pf_17_deta, "Jet_pf_17_deta/F");
  t->Branch("Jet_pf_17_dphi", &Jet_pf_17_dphi, "Jet_pf_17_dphi/F");
  t->Branch("Jet_pf_17_dxy", &Jet_pf_17_dxy, "Jet_pf_17_dxy/F");
  t->Branch("Jet_pf_17_dz", &Jet_pf_17_dz, "Jet_pf_17_dz/F");
  t->Branch("Jet_pf_17_is_chhadron", &Jet_pf_17_is_chhadron, "Jet_pf_17_is_chhadron/O");
  t->Branch("Jet_pf_17_is_ele", &Jet_pf_17_is_ele, "Jet_pf_17_is_ele/O");
  t->Branch("Jet_pf_17_is_muon", &Jet_pf_17_is_muon, "Jet_pf_17_is_muon/O");
  t->Branch("Jet_pf_17_is_nhadron", &Jet_pf_17_is_nhadron, "Jet_pf_17_is_nhadron/O");
  t->Branch("Jet_pf_17_is_photon", &Jet_pf_17_is_photon, "Jet_pf_17_is_photon/O");
  t->Branch("Jet_pf_17_ptfrac", &Jet_pf_17_ptfrac, "Jet_pf_17_ptfrac/F");
  t->Branch("Jet_pf_17_puppiwt", &Jet_pf_17_puppiwt, "Jet_pf_17_puppiwt/F");
  t->Branch("Jet_pf_17_q", &Jet_pf_17_q, "Jet_pf_17_q/B");
  t->Branch("Jet_pf_17_transformed_px", &Jet_pf_17_transformed_px, "Jet_pf_17_transformed_px/F");
  t->Branch("Jet_pf_17_transformed_py", &Jet_pf_17_transformed_py, "Jet_pf_17_transformed_py/F");
  t->Branch("Jet_pf_17_transformed_pz", &Jet_pf_17_transformed_pz, "Jet_pf_17_transformed_pz/F");
  t->Branch("Jet_pf_18_deta", &Jet_pf_18_deta, "Jet_pf_18_deta/F");
  t->Branch("Jet_pf_18_dphi", &Jet_pf_18_dphi, "Jet_pf_18_dphi/F");
  t->Branch("Jet_pf_18_dxy", &Jet_pf_18_dxy, "Jet_pf_18_dxy/F");
  t->Branch("Jet_pf_18_dz", &Jet_pf_18_dz, "Jet_pf_18_dz/F");
  t->Branch("Jet_pf_18_is_chhadron", &Jet_pf_18_is_chhadron, "Jet_pf_18_is_chhadron/O");
  t->Branch("Jet_pf_18_is_ele", &Jet_pf_18_is_ele, "Jet_pf_18_is_ele/O");
  t->Branch("Jet_pf_18_is_muon", &Jet_pf_18_is_muon, "Jet_pf_18_is_muon/O");
  t->Branch("Jet_pf_18_is_nhadron", &Jet_pf_18_is_nhadron, "Jet_pf_18_is_nhadron/O");
  t->Branch("Jet_pf_18_is_photon", &Jet_pf_18_is_photon, "Jet_pf_18_is_photon/O");
  t->Branch("Jet_pf_18_ptfrac", &Jet_pf_18_ptfrac, "Jet_pf_18_ptfrac/F");
  t->Branch("Jet_pf_18_puppiwt", &Jet_pf_18_puppiwt, "Jet_pf_18_puppiwt/F");
  t->Branch("Jet_pf_18_q", &Jet_pf_18_q, "Jet_pf_18_q/B");
  t->Branch("Jet_pf_18_transformed_px", &Jet_pf_18_transformed_px, "Jet_pf_18_transformed_px/F");
  t->Branch("Jet_pf_18_transformed_py", &Jet_pf_18_transformed_py, "Jet_pf_18_transformed_py/F");
  t->Branch("Jet_pf_18_transformed_pz", &Jet_pf_18_transformed_pz, "Jet_pf_18_transformed_pz/F");
  t->Branch("Jet_pf_19_deta", &Jet_pf_19_deta, "Jet_pf_19_deta/F");
  t->Branch("Jet_pf_19_dphi", &Jet_pf_19_dphi, "Jet_pf_19_dphi/F");
  t->Branch("Jet_pf_19_dxy", &Jet_pf_19_dxy, "Jet_pf_19_dxy/F");
  t->Branch("Jet_pf_19_dz", &Jet_pf_19_dz, "Jet_pf_19_dz/F");
  t->Branch("Jet_pf_19_is_chhadron", &Jet_pf_19_is_chhadron, "Jet_pf_19_is_chhadron/O");
  t->Branch("Jet_pf_19_is_ele", &Jet_pf_19_is_ele, "Jet_pf_19_is_ele/O");
  t->Branch("Jet_pf_19_is_muon", &Jet_pf_19_is_muon, "Jet_pf_19_is_muon/O");
  t->Branch("Jet_pf_19_is_nhadron", &Jet_pf_19_is_nhadron, "Jet_pf_19_is_nhadron/O");
  t->Branch("Jet_pf_19_is_photon", &Jet_pf_19_is_photon, "Jet_pf_19_is_photon/O");
  t->Branch("Jet_pf_19_ptfrac", &Jet_pf_19_ptfrac, "Jet_pf_19_ptfrac/F");
  t->Branch("Jet_pf_19_puppiwt", &Jet_pf_19_puppiwt, "Jet_pf_19_puppiwt/F");
  t->Branch("Jet_pf_19_q", &Jet_pf_19_q, "Jet_pf_19_q/B");
  t->Branch("Jet_pf_19_transformed_px", &Jet_pf_19_transformed_px, "Jet_pf_19_transformed_px/F");
  t->Branch("Jet_pf_19_transformed_py", &Jet_pf_19_transformed_py, "Jet_pf_19_transformed_py/F");
  t->Branch("Jet_pf_19_transformed_pz", &Jet_pf_19_transformed_pz, "Jet_pf_19_transformed_pz/F");
  t->Branch("Jet_pf_1_deta", &Jet_pf_1_deta, "Jet_pf_1_deta/F");
  t->Branch("Jet_pf_1_dphi", &Jet_pf_1_dphi, "Jet_pf_1_dphi/F");
  t->Branch("Jet_pf_1_dxy", &Jet_pf_1_dxy, "Jet_pf_1_dxy/F");
  t->Branch("Jet_pf_1_dz", &Jet_pf_1_dz, "Jet_pf_1_dz/F");
  t->Branch("Jet_pf_1_is_chhadron", &Jet_pf_1_is_chhadron, "Jet_pf_1_is_chhadron/O");
  t->Branch("Jet_pf_1_is_ele", &Jet_pf_1_is_ele, "Jet_pf_1_is_ele/O");
  t->Branch("Jet_pf_1_is_muon", &Jet_pf_1_is_muon, "Jet_pf_1_is_muon/O");
  t->Branch("Jet_pf_1_is_nhadron", &Jet_pf_1_is_nhadron, "Jet_pf_1_is_nhadron/O");
  t->Branch("Jet_pf_1_is_photon", &Jet_pf_1_is_photon, "Jet_pf_1_is_photon/O");
  t->Branch("Jet_pf_1_ptfrac", &Jet_pf_1_ptfrac, "Jet_pf_1_ptfrac/F");
  t->Branch("Jet_pf_1_puppiwt", &Jet_pf_1_puppiwt, "Jet_pf_1_puppiwt/F");
  t->Branch("Jet_pf_1_q", &Jet_pf_1_q, "Jet_pf_1_q/B");
  t->Branch("Jet_pf_1_transformed_px", &Jet_pf_1_transformed_px, "Jet_pf_1_transformed_px/F");
  t->Branch("Jet_pf_1_transformed_py", &Jet_pf_1_transformed_py, "Jet_pf_1_transformed_py/F");
  t->Branch("Jet_pf_1_transformed_pz", &Jet_pf_1_transformed_pz, "Jet_pf_1_transformed_pz/F");
  t->Branch("Jet_pf_2_deta", &Jet_pf_2_deta, "Jet_pf_2_deta/F");
  t->Branch("Jet_pf_2_dphi", &Jet_pf_2_dphi, "Jet_pf_2_dphi/F");
  t->Branch("Jet_pf_2_dxy", &Jet_pf_2_dxy, "Jet_pf_2_dxy/F");
  t->Branch("Jet_pf_2_dz", &Jet_pf_2_dz, "Jet_pf_2_dz/F");
  t->Branch("Jet_pf_2_is_chhadron", &Jet_pf_2_is_chhadron, "Jet_pf_2_is_chhadron/O");
  t->Branch("Jet_pf_2_is_ele", &Jet_pf_2_is_ele, "Jet_pf_2_is_ele/O");
  t->Branch("Jet_pf_2_is_muon", &Jet_pf_2_is_muon, "Jet_pf_2_is_muon/O");
  t->Branch("Jet_pf_2_is_nhadron", &Jet_pf_2_is_nhadron, "Jet_pf_2_is_nhadron/O");
  t->Branch("Jet_pf_2_is_photon", &Jet_pf_2_is_photon, "Jet_pf_2_is_photon/O");
  t->Branch("Jet_pf_2_ptfrac", &Jet_pf_2_ptfrac, "Jet_pf_2_ptfrac/F");
  t->Branch("Jet_pf_2_puppiwt", &Jet_pf_2_puppiwt, "Jet_pf_2_puppiwt/F");
  t->Branch("Jet_pf_2_q", &Jet_pf_2_q, "Jet_pf_2_q/B");
  t->Branch("Jet_pf_2_transformed_px", &Jet_pf_2_transformed_px, "Jet_pf_2_transformed_px/F");
  t->Branch("Jet_pf_2_transformed_py", &Jet_pf_2_transformed_py, "Jet_pf_2_transformed_py/F");
  t->Branch("Jet_pf_2_transformed_pz", &Jet_pf_2_transformed_pz, "Jet_pf_2_transformed_pz/F");
  t->Branch("Jet_pf_3_deta", &Jet_pf_3_deta, "Jet_pf_3_deta/F");
  t->Branch("Jet_pf_3_dphi", &Jet_pf_3_dphi, "Jet_pf_3_dphi/F");
  t->Branch("Jet_pf_3_dxy", &Jet_pf_3_dxy, "Jet_pf_3_dxy/F");
  t->Branch("Jet_pf_3_dz", &Jet_pf_3_dz, "Jet_pf_3_dz/F");
  t->Branch("Jet_pf_3_is_chhadron", &Jet_pf_3_is_chhadron, "Jet_pf_3_is_chhadron/O");
  t->Branch("Jet_pf_3_is_ele", &Jet_pf_3_is_ele, "Jet_pf_3_is_ele/O");
  t->Branch("Jet_pf_3_is_muon", &Jet_pf_3_is_muon, "Jet_pf_3_is_muon/O");
  t->Branch("Jet_pf_3_is_nhadron", &Jet_pf_3_is_nhadron, "Jet_pf_3_is_nhadron/O");
  t->Branch("Jet_pf_3_is_photon", &Jet_pf_3_is_photon, "Jet_pf_3_is_photon/O");
  t->Branch("Jet_pf_3_ptfrac", &Jet_pf_3_ptfrac, "Jet_pf_3_ptfrac/F");
  t->Branch("Jet_pf_3_puppiwt", &Jet_pf_3_puppiwt, "Jet_pf_3_puppiwt/F");
  t->Branch("Jet_pf_3_q", &Jet_pf_3_q, "Jet_pf_3_q/B");
  t->Branch("Jet_pf_3_transformed_px", &Jet_pf_3_transformed_px, "Jet_pf_3_transformed_px/F");
  t->Branch("Jet_pf_3_transformed_py", &Jet_pf_3_transformed_py, "Jet_pf_3_transformed_py/F");
  t->Branch("Jet_pf_3_transformed_pz", &Jet_pf_3_transformed_pz, "Jet_pf_3_transformed_pz/F");
  t->Branch("Jet_pf_4_deta", &Jet_pf_4_deta, "Jet_pf_4_deta/F");
  t->Branch("Jet_pf_4_dphi", &Jet_pf_4_dphi, "Jet_pf_4_dphi/F");
  t->Branch("Jet_pf_4_dxy", &Jet_pf_4_dxy, "Jet_pf_4_dxy/F");
  t->Branch("Jet_pf_4_dz", &Jet_pf_4_dz, "Jet_pf_4_dz/F");
  t->Branch("Jet_pf_4_is_chhadron", &Jet_pf_4_is_chhadron, "Jet_pf_4_is_chhadron/O");
  t->Branch("Jet_pf_4_is_ele", &Jet_pf_4_is_ele, "Jet_pf_4_is_ele/O");
  t->Branch("Jet_pf_4_is_muon", &Jet_pf_4_is_muon, "Jet_pf_4_is_muon/O");
  t->Branch("Jet_pf_4_is_nhadron", &Jet_pf_4_is_nhadron, "Jet_pf_4_is_nhadron/O");
  t->Branch("Jet_pf_4_is_photon", &Jet_pf_4_is_photon, "Jet_pf_4_is_photon/O");
  t->Branch("Jet_pf_4_ptfrac", &Jet_pf_4_ptfrac, "Jet_pf_4_ptfrac/F");
  t->Branch("Jet_pf_4_puppiwt", &Jet_pf_4_puppiwt, "Jet_pf_4_puppiwt/F");
  t->Branch("Jet_pf_4_q", &Jet_pf_4_q, "Jet_pf_4_q/B");
  t->Branch("Jet_pf_4_transformed_px", &Jet_pf_4_transformed_px, "Jet_pf_4_transformed_px/F");
  t->Branch("Jet_pf_4_transformed_py", &Jet_pf_4_transformed_py, "Jet_pf_4_transformed_py/F");
  t->Branch("Jet_pf_4_transformed_pz", &Jet_pf_4_transformed_pz, "Jet_pf_4_transformed_pz/F");
  t->Branch("Jet_pf_5_deta", &Jet_pf_5_deta, "Jet_pf_5_deta/F");
  t->Branch("Jet_pf_5_dphi", &Jet_pf_5_dphi, "Jet_pf_5_dphi/F");
  t->Branch("Jet_pf_5_dxy", &Jet_pf_5_dxy, "Jet_pf_5_dxy/F");
  t->Branch("Jet_pf_5_dz", &Jet_pf_5_dz, "Jet_pf_5_dz/F");
  t->Branch("Jet_pf_5_is_chhadron", &Jet_pf_5_is_chhadron, "Jet_pf_5_is_chhadron/O");
  t->Branch("Jet_pf_5_is_ele", &Jet_pf_5_is_ele, "Jet_pf_5_is_ele/O");
  t->Branch("Jet_pf_5_is_muon", &Jet_pf_5_is_muon, "Jet_pf_5_is_muon/O");
  t->Branch("Jet_pf_5_is_nhadron", &Jet_pf_5_is_nhadron, "Jet_pf_5_is_nhadron/O");
  t->Branch("Jet_pf_5_is_photon", &Jet_pf_5_is_photon, "Jet_pf_5_is_photon/O");
  t->Branch("Jet_pf_5_ptfrac", &Jet_pf_5_ptfrac, "Jet_pf_5_ptfrac/F");
  t->Branch("Jet_pf_5_puppiwt", &Jet_pf_5_puppiwt, "Jet_pf_5_puppiwt/F");
  t->Branch("Jet_pf_5_q", &Jet_pf_5_q, "Jet_pf_5_q/B");
  t->Branch("Jet_pf_5_transformed_px", &Jet_pf_5_transformed_px, "Jet_pf_5_transformed_px/F");
  t->Branch("Jet_pf_5_transformed_py", &Jet_pf_5_transformed_py, "Jet_pf_5_transformed_py/F");
  t->Branch("Jet_pf_5_transformed_pz", &Jet_pf_5_transformed_pz, "Jet_pf_5_transformed_pz/F");
  t->Branch("Jet_pf_6_deta", &Jet_pf_6_deta, "Jet_pf_6_deta/F");
  t->Branch("Jet_pf_6_dphi", &Jet_pf_6_dphi, "Jet_pf_6_dphi/F");
  t->Branch("Jet_pf_6_dxy", &Jet_pf_6_dxy, "Jet_pf_6_dxy/F");
  t->Branch("Jet_pf_6_dz", &Jet_pf_6_dz, "Jet_pf_6_dz/F");
  t->Branch("Jet_pf_6_is_chhadron", &Jet_pf_6_is_chhadron, "Jet_pf_6_is_chhadron/O");
  t->Branch("Jet_pf_6_is_ele", &Jet_pf_6_is_ele, "Jet_pf_6_is_ele/O");
  t->Branch("Jet_pf_6_is_muon", &Jet_pf_6_is_muon, "Jet_pf_6_is_muon/O");
  t->Branch("Jet_pf_6_is_nhadron", &Jet_pf_6_is_nhadron, "Jet_pf_6_is_nhadron/O");
  t->Branch("Jet_pf_6_is_photon", &Jet_pf_6_is_photon, "Jet_pf_6_is_photon/O");
  t->Branch("Jet_pf_6_ptfrac", &Jet_pf_6_ptfrac, "Jet_pf_6_ptfrac/F");
  t->Branch("Jet_pf_6_puppiwt", &Jet_pf_6_puppiwt, "Jet_pf_6_puppiwt/F");
  t->Branch("Jet_pf_6_q", &Jet_pf_6_q, "Jet_pf_6_q/B");
  t->Branch("Jet_pf_6_transformed_px", &Jet_pf_6_transformed_px, "Jet_pf_6_transformed_px/F");
  t->Branch("Jet_pf_6_transformed_py", &Jet_pf_6_transformed_py, "Jet_pf_6_transformed_py/F");
  t->Branch("Jet_pf_6_transformed_pz", &Jet_pf_6_transformed_pz, "Jet_pf_6_transformed_pz/F");
  t->Branch("Jet_pf_7_deta", &Jet_pf_7_deta, "Jet_pf_7_deta/F");
  t->Branch("Jet_pf_7_dphi", &Jet_pf_7_dphi, "Jet_pf_7_dphi/F");
  t->Branch("Jet_pf_7_dxy", &Jet_pf_7_dxy, "Jet_pf_7_dxy/F");
  t->Branch("Jet_pf_7_dz", &Jet_pf_7_dz, "Jet_pf_7_dz/F");
  t->Branch("Jet_pf_7_is_chhadron", &Jet_pf_7_is_chhadron, "Jet_pf_7_is_chhadron/O");
  t->Branch("Jet_pf_7_is_ele", &Jet_pf_7_is_ele, "Jet_pf_7_is_ele/O");
  t->Branch("Jet_pf_7_is_muon", &Jet_pf_7_is_muon, "Jet_pf_7_is_muon/O");
  t->Branch("Jet_pf_7_is_nhadron", &Jet_pf_7_is_nhadron, "Jet_pf_7_is_nhadron/O");
  t->Branch("Jet_pf_7_is_photon", &Jet_pf_7_is_photon, "Jet_pf_7_is_photon/O");
  t->Branch("Jet_pf_7_ptfrac", &Jet_pf_7_ptfrac, "Jet_pf_7_ptfrac/F");
  t->Branch("Jet_pf_7_puppiwt", &Jet_pf_7_puppiwt, "Jet_pf_7_puppiwt/F");
  t->Branch("Jet_pf_7_q", &Jet_pf_7_q, "Jet_pf_7_q/B");
  t->Branch("Jet_pf_7_transformed_px", &Jet_pf_7_transformed_px, "Jet_pf_7_transformed_px/F");
  t->Branch("Jet_pf_7_transformed_py", &Jet_pf_7_transformed_py, "Jet_pf_7_transformed_py/F");
  t->Branch("Jet_pf_7_transformed_pz", &Jet_pf_7_transformed_pz, "Jet_pf_7_transformed_pz/F");
  t->Branch("Jet_pf_8_deta", &Jet_pf_8_deta, "Jet_pf_8_deta/F");
  t->Branch("Jet_pf_8_dphi", &Jet_pf_8_dphi, "Jet_pf_8_dphi/F");
  t->Branch("Jet_pf_8_dxy", &Jet_pf_8_dxy, "Jet_pf_8_dxy/F");
  t->Branch("Jet_pf_8_dz", &Jet_pf_8_dz, "Jet_pf_8_dz/F");
  t->Branch("Jet_pf_8_is_chhadron", &Jet_pf_8_is_chhadron, "Jet_pf_8_is_chhadron/O");
  t->Branch("Jet_pf_8_is_ele", &Jet_pf_8_is_ele, "Jet_pf_8_is_ele/O");
  t->Branch("Jet_pf_8_is_muon", &Jet_pf_8_is_muon, "Jet_pf_8_is_muon/O");
  t->Branch("Jet_pf_8_is_nhadron", &Jet_pf_8_is_nhadron, "Jet_pf_8_is_nhadron/O");
  t->Branch("Jet_pf_8_is_photon", &Jet_pf_8_is_photon, "Jet_pf_8_is_photon/O");
  t->Branch("Jet_pf_8_ptfrac", &Jet_pf_8_ptfrac, "Jet_pf_8_ptfrac/F");
  t->Branch("Jet_pf_8_puppiwt", &Jet_pf_8_puppiwt, "Jet_pf_8_puppiwt/F");
  t->Branch("Jet_pf_8_q", &Jet_pf_8_q, "Jet_pf_8_q/B");
  t->Branch("Jet_pf_8_transformed_px", &Jet_pf_8_transformed_px, "Jet_pf_8_transformed_px/F");
  t->Branch("Jet_pf_8_transformed_py", &Jet_pf_8_transformed_py, "Jet_pf_8_transformed_py/F");
  t->Branch("Jet_pf_8_transformed_pz", &Jet_pf_8_transformed_pz, "Jet_pf_8_transformed_pz/F");
  t->Branch("Jet_pf_9_deta", &Jet_pf_9_deta, "Jet_pf_9_deta/F");
  t->Branch("Jet_pf_9_dphi", &Jet_pf_9_dphi, "Jet_pf_9_dphi/F");
  t->Branch("Jet_pf_9_dxy", &Jet_pf_9_dxy, "Jet_pf_9_dxy/F");
  t->Branch("Jet_pf_9_dz", &Jet_pf_9_dz, "Jet_pf_9_dz/F");
  t->Branch("Jet_pf_9_is_chhadron", &Jet_pf_9_is_chhadron, "Jet_pf_9_is_chhadron/O");
  t->Branch("Jet_pf_9_is_ele", &Jet_pf_9_is_ele, "Jet_pf_9_is_ele/O");
  t->Branch("Jet_pf_9_is_muon", &Jet_pf_9_is_muon, "Jet_pf_9_is_muon/O");
  t->Branch("Jet_pf_9_is_nhadron", &Jet_pf_9_is_nhadron, "Jet_pf_9_is_nhadron/O");
  t->Branch("Jet_pf_9_is_photon", &Jet_pf_9_is_photon, "Jet_pf_9_is_photon/O");
  t->Branch("Jet_pf_9_ptfrac", &Jet_pf_9_ptfrac, "Jet_pf_9_ptfrac/F");
  t->Branch("Jet_pf_9_puppiwt", &Jet_pf_9_puppiwt, "Jet_pf_9_puppiwt/F");
  t->Branch("Jet_pf_9_q", &Jet_pf_9_q, "Jet_pf_9_q/B");
  t->Branch("Jet_pf_9_transformed_px", &Jet_pf_9_transformed_px, "Jet_pf_9_transformed_px/F");
  t->Branch("Jet_pf_9_transformed_py", &Jet_pf_9_transformed_py, "Jet_pf_9_transformed_py/F");
  t->Branch("Jet_pf_9_transformed_pz", &Jet_pf_9_transformed_pz, "Jet_pf_9_transformed_pz/F");
  t->Branch("Jet_phi", &Jet_phi, "Jet_phi/F");
  t->Branch("Jet_pt", &Jet_pt, "Jet_pt/F");
  t->Branch("Jet_puId", &Jet_puId, "Jet_puId/F");
  t->Branch("Jet_raw", &Jet_raw, "Jet_raw/F");
  t->Branch("event", &event, "event/l");
  t->Branch("genWeight", &genWeight, "genWeight/F");
  t->Branch("luminosityBlock", &luminosityBlock, "luminosityBlock/l");
  t->Branch("met_phi", &met_phi, "met_phi/F");
  t->Branch("met_pt", &met_pt, "met_pt/F");
  t->Branch("nPVs", &nPVs, "nPVs/F");
  t->Branch("nPVs_good", &nPVs_good, "nPVs_good/F");
  t->Branch("rho", &rho, "rho/F");
  t->Branch("run", &run, "run/i");
}

void regfile::reset(const panda::Event& e) {
  Jet_btagCMVA = 0;
  Jet_btagDeepB = 0;
  Jet_btagDeepC = 0;
  Jet_chEmEF = 0;
  Jet_chHEF = 0;
  Jet_e = 0;
  Jet_eta = 0;
  Jet_mass = 0;
  Jet_mcEta = 0;
  Jet_mcFlavour = 0;
  Jet_mcM = 0;
  Jet_mcPhi = 0;
  Jet_mcPt = 0;
  Jet_met_dPhi = 0;
  Jet_mt = 0;
  Jet_neEmEF = 0;
  Jet_neHEF = 0;
  Jet_numberOfDaughters = 0;
  Jet_pf_0_deta = 0;
  Jet_pf_0_dphi = 0;
  Jet_pf_0_dxy = 0;
  Jet_pf_0_dz = 0;
  Jet_pf_0_is_chhadron = 0;
  Jet_pf_0_is_ele = 0;
  Jet_pf_0_is_muon = 0;
  Jet_pf_0_is_nhadron = 0;
  Jet_pf_0_is_photon = 0;
  Jet_pf_0_ptfrac = 0;
  Jet_pf_0_puppiwt = 0;
  Jet_pf_0_q = 0;
  Jet_pf_0_transformed_px = 0;
  Jet_pf_0_transformed_py = 0;
  Jet_pf_0_transformed_pz = 0;
  Jet_pf_10_deta = 0;
  Jet_pf_10_dphi = 0;
  Jet_pf_10_dxy = 0;
  Jet_pf_10_dz = 0;
  Jet_pf_10_is_chhadron = 0;
  Jet_pf_10_is_ele = 0;
  Jet_pf_10_is_muon = 0;
  Jet_pf_10_is_nhadron = 0;
  Jet_pf_10_is_photon = 0;
  Jet_pf_10_ptfrac = 0;
  Jet_pf_10_puppiwt = 0;
  Jet_pf_10_q = 0;
  Jet_pf_10_transformed_px = 0;
  Jet_pf_10_transformed_py = 0;
  Jet_pf_10_transformed_pz = 0;
  Jet_pf_11_deta = 0;
  Jet_pf_11_dphi = 0;
  Jet_pf_11_dxy = 0;
  Jet_pf_11_dz = 0;
  Jet_pf_11_is_chhadron = 0;
  Jet_pf_11_is_ele = 0;
  Jet_pf_11_is_muon = 0;
  Jet_pf_11_is_nhadron = 0;
  Jet_pf_11_is_photon = 0;
  Jet_pf_11_ptfrac = 0;
  Jet_pf_11_puppiwt = 0;
  Jet_pf_11_q = 0;
  Jet_pf_11_transformed_px = 0;
  Jet_pf_11_transformed_py = 0;
  Jet_pf_11_transformed_pz = 0;
  Jet_pf_12_deta = 0;
  Jet_pf_12_dphi = 0;
  Jet_pf_12_dxy = 0;
  Jet_pf_12_dz = 0;
  Jet_pf_12_is_chhadron = 0;
  Jet_pf_12_is_ele = 0;
  Jet_pf_12_is_muon = 0;
  Jet_pf_12_is_nhadron = 0;
  Jet_pf_12_is_photon = 0;
  Jet_pf_12_ptfrac = 0;
  Jet_pf_12_puppiwt = 0;
  Jet_pf_12_q = 0;
  Jet_pf_12_transformed_px = 0;
  Jet_pf_12_transformed_py = 0;
  Jet_pf_12_transformed_pz = 0;
  Jet_pf_13_deta = 0;
  Jet_pf_13_dphi = 0;
  Jet_pf_13_dxy = 0;
  Jet_pf_13_dz = 0;
  Jet_pf_13_is_chhadron = 0;
  Jet_pf_13_is_ele = 0;
  Jet_pf_13_is_muon = 0;
  Jet_pf_13_is_nhadron = 0;
  Jet_pf_13_is_photon = 0;
  Jet_pf_13_ptfrac = 0;
  Jet_pf_13_puppiwt = 0;
  Jet_pf_13_q = 0;
  Jet_pf_13_transformed_px = 0;
  Jet_pf_13_transformed_py = 0;
  Jet_pf_13_transformed_pz = 0;
  Jet_pf_14_deta = 0;
  Jet_pf_14_dphi = 0;
  Jet_pf_14_dxy = 0;
  Jet_pf_14_dz = 0;
  Jet_pf_14_is_chhadron = 0;
  Jet_pf_14_is_ele = 0;
  Jet_pf_14_is_muon = 0;
  Jet_pf_14_is_nhadron = 0;
  Jet_pf_14_is_photon = 0;
  Jet_pf_14_ptfrac = 0;
  Jet_pf_14_puppiwt = 0;
  Jet_pf_14_q = 0;
  Jet_pf_14_transformed_px = 0;
  Jet_pf_14_transformed_py = 0;
  Jet_pf_14_transformed_pz = 0;
  Jet_pf_15_deta = 0;
  Jet_pf_15_dphi = 0;
  Jet_pf_15_dxy = 0;
  Jet_pf_15_dz = 0;
  Jet_pf_15_is_chhadron = 0;
  Jet_pf_15_is_ele = 0;
  Jet_pf_15_is_muon = 0;
  Jet_pf_15_is_nhadron = 0;
  Jet_pf_15_is_photon = 0;
  Jet_pf_15_ptfrac = 0;
  Jet_pf_15_puppiwt = 0;
  Jet_pf_15_q = 0;
  Jet_pf_15_transformed_px = 0;
  Jet_pf_15_transformed_py = 0;
  Jet_pf_15_transformed_pz = 0;
  Jet_pf_16_deta = 0;
  Jet_pf_16_dphi = 0;
  Jet_pf_16_dxy = 0;
  Jet_pf_16_dz = 0;
  Jet_pf_16_is_chhadron = 0;
  Jet_pf_16_is_ele = 0;
  Jet_pf_16_is_muon = 0;
  Jet_pf_16_is_nhadron = 0;
  Jet_pf_16_is_photon = 0;
  Jet_pf_16_ptfrac = 0;
  Jet_pf_16_puppiwt = 0;
  Jet_pf_16_q = 0;
  Jet_pf_16_transformed_px = 0;
  Jet_pf_16_transformed_py = 0;
  Jet_pf_16_transformed_pz = 0;
  Jet_pf_17_deta = 0;
  Jet_pf_17_dphi = 0;
  Jet_pf_17_dxy = 0;
  Jet_pf_17_dz = 0;
  Jet_pf_17_is_chhadron = 0;
  Jet_pf_17_is_ele = 0;
  Jet_pf_17_is_muon = 0;
  Jet_pf_17_is_nhadron = 0;
  Jet_pf_17_is_photon = 0;
  Jet_pf_17_ptfrac = 0;
  Jet_pf_17_puppiwt = 0;
  Jet_pf_17_q = 0;
  Jet_pf_17_transformed_px = 0;
  Jet_pf_17_transformed_py = 0;
  Jet_pf_17_transformed_pz = 0;
  Jet_pf_18_deta = 0;
  Jet_pf_18_dphi = 0;
  Jet_pf_18_dxy = 0;
  Jet_pf_18_dz = 0;
  Jet_pf_18_is_chhadron = 0;
  Jet_pf_18_is_ele = 0;
  Jet_pf_18_is_muon = 0;
  Jet_pf_18_is_nhadron = 0;
  Jet_pf_18_is_photon = 0;
  Jet_pf_18_ptfrac = 0;
  Jet_pf_18_puppiwt = 0;
  Jet_pf_18_q = 0;
  Jet_pf_18_transformed_px = 0;
  Jet_pf_18_transformed_py = 0;
  Jet_pf_18_transformed_pz = 0;
  Jet_pf_19_deta = 0;
  Jet_pf_19_dphi = 0;
  Jet_pf_19_dxy = 0;
  Jet_pf_19_dz = 0;
  Jet_pf_19_is_chhadron = 0;
  Jet_pf_19_is_ele = 0;
  Jet_pf_19_is_muon = 0;
  Jet_pf_19_is_nhadron = 0;
  Jet_pf_19_is_photon = 0;
  Jet_pf_19_ptfrac = 0;
  Jet_pf_19_puppiwt = 0;
  Jet_pf_19_q = 0;
  Jet_pf_19_transformed_px = 0;
  Jet_pf_19_transformed_py = 0;
  Jet_pf_19_transformed_pz = 0;
  Jet_pf_1_deta = 0;
  Jet_pf_1_dphi = 0;
  Jet_pf_1_dxy = 0;
  Jet_pf_1_dz = 0;
  Jet_pf_1_is_chhadron = 0;
  Jet_pf_1_is_ele = 0;
  Jet_pf_1_is_muon = 0;
  Jet_pf_1_is_nhadron = 0;
  Jet_pf_1_is_photon = 0;
  Jet_pf_1_ptfrac = 0;
  Jet_pf_1_puppiwt = 0;
  Jet_pf_1_q = 0;
  Jet_pf_1_transformed_px = 0;
  Jet_pf_1_transformed_py = 0;
  Jet_pf_1_transformed_pz = 0;
  Jet_pf_2_deta = 0;
  Jet_pf_2_dphi = 0;
  Jet_pf_2_dxy = 0;
  Jet_pf_2_dz = 0;
  Jet_pf_2_is_chhadron = 0;
  Jet_pf_2_is_ele = 0;
  Jet_pf_2_is_muon = 0;
  Jet_pf_2_is_nhadron = 0;
  Jet_pf_2_is_photon = 0;
  Jet_pf_2_ptfrac = 0;
  Jet_pf_2_puppiwt = 0;
  Jet_pf_2_q = 0;
  Jet_pf_2_transformed_px = 0;
  Jet_pf_2_transformed_py = 0;
  Jet_pf_2_transformed_pz = 0;
  Jet_pf_3_deta = 0;
  Jet_pf_3_dphi = 0;
  Jet_pf_3_dxy = 0;
  Jet_pf_3_dz = 0;
  Jet_pf_3_is_chhadron = 0;
  Jet_pf_3_is_ele = 0;
  Jet_pf_3_is_muon = 0;
  Jet_pf_3_is_nhadron = 0;
  Jet_pf_3_is_photon = 0;
  Jet_pf_3_ptfrac = 0;
  Jet_pf_3_puppiwt = 0;
  Jet_pf_3_q = 0;
  Jet_pf_3_transformed_px = 0;
  Jet_pf_3_transformed_py = 0;
  Jet_pf_3_transformed_pz = 0;
  Jet_pf_4_deta = 0;
  Jet_pf_4_dphi = 0;
  Jet_pf_4_dxy = 0;
  Jet_pf_4_dz = 0;
  Jet_pf_4_is_chhadron = 0;
  Jet_pf_4_is_ele = 0;
  Jet_pf_4_is_muon = 0;
  Jet_pf_4_is_nhadron = 0;
  Jet_pf_4_is_photon = 0;
  Jet_pf_4_ptfrac = 0;
  Jet_pf_4_puppiwt = 0;
  Jet_pf_4_q = 0;
  Jet_pf_4_transformed_px = 0;
  Jet_pf_4_transformed_py = 0;
  Jet_pf_4_transformed_pz = 0;
  Jet_pf_5_deta = 0;
  Jet_pf_5_dphi = 0;
  Jet_pf_5_dxy = 0;
  Jet_pf_5_dz = 0;
  Jet_pf_5_is_chhadron = 0;
  Jet_pf_5_is_ele = 0;
  Jet_pf_5_is_muon = 0;
  Jet_pf_5_is_nhadron = 0;
  Jet_pf_5_is_photon = 0;
  Jet_pf_5_ptfrac = 0;
  Jet_pf_5_puppiwt = 0;
  Jet_pf_5_q = 0;
  Jet_pf_5_transformed_px = 0;
  Jet_pf_5_transformed_py = 0;
  Jet_pf_5_transformed_pz = 0;
  Jet_pf_6_deta = 0;
  Jet_pf_6_dphi = 0;
  Jet_pf_6_dxy = 0;
  Jet_pf_6_dz = 0;
  Jet_pf_6_is_chhadron = 0;
  Jet_pf_6_is_ele = 0;
  Jet_pf_6_is_muon = 0;
  Jet_pf_6_is_nhadron = 0;
  Jet_pf_6_is_photon = 0;
  Jet_pf_6_ptfrac = 0;
  Jet_pf_6_puppiwt = 0;
  Jet_pf_6_q = 0;
  Jet_pf_6_transformed_px = 0;
  Jet_pf_6_transformed_py = 0;
  Jet_pf_6_transformed_pz = 0;
  Jet_pf_7_deta = 0;
  Jet_pf_7_dphi = 0;
  Jet_pf_7_dxy = 0;
  Jet_pf_7_dz = 0;
  Jet_pf_7_is_chhadron = 0;
  Jet_pf_7_is_ele = 0;
  Jet_pf_7_is_muon = 0;
  Jet_pf_7_is_nhadron = 0;
  Jet_pf_7_is_photon = 0;
  Jet_pf_7_ptfrac = 0;
  Jet_pf_7_puppiwt = 0;
  Jet_pf_7_q = 0;
  Jet_pf_7_transformed_px = 0;
  Jet_pf_7_transformed_py = 0;
  Jet_pf_7_transformed_pz = 0;
  Jet_pf_8_deta = 0;
  Jet_pf_8_dphi = 0;
  Jet_pf_8_dxy = 0;
  Jet_pf_8_dz = 0;
  Jet_pf_8_is_chhadron = 0;
  Jet_pf_8_is_ele = 0;
  Jet_pf_8_is_muon = 0;
  Jet_pf_8_is_nhadron = 0;
  Jet_pf_8_is_photon = 0;
  Jet_pf_8_ptfrac = 0;
  Jet_pf_8_puppiwt = 0;
  Jet_pf_8_q = 0;
  Jet_pf_8_transformed_px = 0;
  Jet_pf_8_transformed_py = 0;
  Jet_pf_8_transformed_pz = 0;
  Jet_pf_9_deta = 0;
  Jet_pf_9_dphi = 0;
  Jet_pf_9_dxy = 0;
  Jet_pf_9_dz = 0;
  Jet_pf_9_is_chhadron = 0;
  Jet_pf_9_is_ele = 0;
  Jet_pf_9_is_muon = 0;
  Jet_pf_9_is_nhadron = 0;
  Jet_pf_9_is_photon = 0;
  Jet_pf_9_ptfrac = 0;
  Jet_pf_9_puppiwt = 0;
  Jet_pf_9_q = 0;
  Jet_pf_9_transformed_px = 0;
  Jet_pf_9_transformed_py = 0;
  Jet_pf_9_transformed_pz = 0;
  Jet_phi = 0;
  Jet_pt = 0;
  Jet_puId = 0;
  Jet_raw = 0;
  event = e.eventNumber;
  genWeight = e.weight;
  luminosityBlock = e.lumiNumber;
  met_phi = e.pfMet.phi;
  met_pt = e.pfMet.pt;
  nPVs = e.npvTrue;
  nPVs_good = e.npv;
  pv = e.vertices[0].position();
  rho = e.rho;
  run = e.runNumber;
}

void regfile::fill() {
  Jet_met_dPhi = TVector2::Phi_mpi_pi(met_phi - Jet_phi);
  t->Fill();
}

template <typename G> void regfile::set_jet(const jet base, const panda::Jet& jet, const gennujet::GenNuVec& withnu, const G gen) {
  auto p4 = jet.p4();
  auto pfvecs = pfvecs::get_vecs(jet, pv);
  switch(base) {
  case regfile::jet::Jet:
    Jet_puId = jet.puid;
    Jet_btagCMVA = jet.cmva;
    Jet_btagDeepC = jet.deepCSVc + jet.deepCSVcc;
    Jet_btagDeepB = jet.deepCSVb + jet.deepCSVbb;
    Jet_raw = jet.rawPt/jet.pt();
    Jet_pt = p4.Pt();
    Jet_eta = p4.Eta();
    Jet_phi = p4.Phi();
    Jet_mt = p4.Mt();
    Jet_e = p4.E();
    Jet_mass = p4.M();
    Jet_chHEF = jet.chf;
    Jet_neHEF = jet.nhf;
    Jet_chEmEF = jet.cef;
    Jet_neEmEF = jet.nef;
    Jet_mcPt = withnu.genvec.Pt();
    Jet_mcEta = withnu.genvec.Eta();
    Jet_mcPhi = withnu.genvec.Phi();
    Jet_mcM = withnu.genvec.M();
    Jet_mcFlavour = gen->partonFlavor;
    Jet_numberOfDaughters = jet.constituents.size();
    Jet_pf_0_ptfrac = (pfvecs.size() > 0) ? pfvecs[0].ptfrac : -50;
    Jet_pf_0_deta = (pfvecs.size() > 0) ? pfvecs[0].deta : -50;
    Jet_pf_0_dphi = (pfvecs.size() > 0) ? pfvecs[0].dphi : -50;
    Jet_pf_0_puppiwt = (pfvecs.size() > 0) ? pfvecs[0].puppiwt : -50;
    Jet_pf_0_dxy = (pfvecs.size() > 0) ? pfvecs[0].dxy : -50;
    Jet_pf_0_dz = (pfvecs.size() > 0) ? pfvecs[0].dz : -50;
    Jet_pf_1_ptfrac = (pfvecs.size() > 1) ? pfvecs[1].ptfrac : -50;
    Jet_pf_1_deta = (pfvecs.size() > 1) ? pfvecs[1].deta : -50;
    Jet_pf_1_dphi = (pfvecs.size() > 1) ? pfvecs[1].dphi : -50;
    Jet_pf_1_puppiwt = (pfvecs.size() > 1) ? pfvecs[1].puppiwt : -50;
    Jet_pf_1_dxy = (pfvecs.size() > 1) ? pfvecs[1].dxy : -50;
    Jet_pf_1_dz = (pfvecs.size() > 1) ? pfvecs[1].dz : -50;
    Jet_pf_2_ptfrac = (pfvecs.size() > 2) ? pfvecs[2].ptfrac : -50;
    Jet_pf_2_deta = (pfvecs.size() > 2) ? pfvecs[2].deta : -50;
    Jet_pf_2_dphi = (pfvecs.size() > 2) ? pfvecs[2].dphi : -50;
    Jet_pf_2_puppiwt = (pfvecs.size() > 2) ? pfvecs[2].puppiwt : -50;
    Jet_pf_2_dxy = (pfvecs.size() > 2) ? pfvecs[2].dxy : -50;
    Jet_pf_2_dz = (pfvecs.size() > 2) ? pfvecs[2].dz : -50;
    Jet_pf_3_ptfrac = (pfvecs.size() > 3) ? pfvecs[3].ptfrac : -50;
    Jet_pf_3_deta = (pfvecs.size() > 3) ? pfvecs[3].deta : -50;
    Jet_pf_3_dphi = (pfvecs.size() > 3) ? pfvecs[3].dphi : -50;
    Jet_pf_3_puppiwt = (pfvecs.size() > 3) ? pfvecs[3].puppiwt : -50;
    Jet_pf_3_dxy = (pfvecs.size() > 3) ? pfvecs[3].dxy : -50;
    Jet_pf_3_dz = (pfvecs.size() > 3) ? pfvecs[3].dz : -50;
    Jet_pf_4_ptfrac = (pfvecs.size() > 4) ? pfvecs[4].ptfrac : -50;
    Jet_pf_4_deta = (pfvecs.size() > 4) ? pfvecs[4].deta : -50;
    Jet_pf_4_dphi = (pfvecs.size() > 4) ? pfvecs[4].dphi : -50;
    Jet_pf_4_puppiwt = (pfvecs.size() > 4) ? pfvecs[4].puppiwt : -50;
    Jet_pf_4_dxy = (pfvecs.size() > 4) ? pfvecs[4].dxy : -50;
    Jet_pf_4_dz = (pfvecs.size() > 4) ? pfvecs[4].dz : -50;
    Jet_pf_5_ptfrac = (pfvecs.size() > 5) ? pfvecs[5].ptfrac : -50;
    Jet_pf_5_deta = (pfvecs.size() > 5) ? pfvecs[5].deta : -50;
    Jet_pf_5_dphi = (pfvecs.size() > 5) ? pfvecs[5].dphi : -50;
    Jet_pf_5_puppiwt = (pfvecs.size() > 5) ? pfvecs[5].puppiwt : -50;
    Jet_pf_5_dxy = (pfvecs.size() > 5) ? pfvecs[5].dxy : -50;
    Jet_pf_5_dz = (pfvecs.size() > 5) ? pfvecs[5].dz : -50;
    Jet_pf_6_ptfrac = (pfvecs.size() > 6) ? pfvecs[6].ptfrac : -50;
    Jet_pf_6_deta = (pfvecs.size() > 6) ? pfvecs[6].deta : -50;
    Jet_pf_6_dphi = (pfvecs.size() > 6) ? pfvecs[6].dphi : -50;
    Jet_pf_6_puppiwt = (pfvecs.size() > 6) ? pfvecs[6].puppiwt : -50;
    Jet_pf_6_dxy = (pfvecs.size() > 6) ? pfvecs[6].dxy : -50;
    Jet_pf_6_dz = (pfvecs.size() > 6) ? pfvecs[6].dz : -50;
    Jet_pf_7_ptfrac = (pfvecs.size() > 7) ? pfvecs[7].ptfrac : -50;
    Jet_pf_7_deta = (pfvecs.size() > 7) ? pfvecs[7].deta : -50;
    Jet_pf_7_dphi = (pfvecs.size() > 7) ? pfvecs[7].dphi : -50;
    Jet_pf_7_puppiwt = (pfvecs.size() > 7) ? pfvecs[7].puppiwt : -50;
    Jet_pf_7_dxy = (pfvecs.size() > 7) ? pfvecs[7].dxy : -50;
    Jet_pf_7_dz = (pfvecs.size() > 7) ? pfvecs[7].dz : -50;
    Jet_pf_8_ptfrac = (pfvecs.size() > 8) ? pfvecs[8].ptfrac : -50;
    Jet_pf_8_deta = (pfvecs.size() > 8) ? pfvecs[8].deta : -50;
    Jet_pf_8_dphi = (pfvecs.size() > 8) ? pfvecs[8].dphi : -50;
    Jet_pf_8_puppiwt = (pfvecs.size() > 8) ? pfvecs[8].puppiwt : -50;
    Jet_pf_8_dxy = (pfvecs.size() > 8) ? pfvecs[8].dxy : -50;
    Jet_pf_8_dz = (pfvecs.size() > 8) ? pfvecs[8].dz : -50;
    Jet_pf_9_ptfrac = (pfvecs.size() > 9) ? pfvecs[9].ptfrac : -50;
    Jet_pf_9_deta = (pfvecs.size() > 9) ? pfvecs[9].deta : -50;
    Jet_pf_9_dphi = (pfvecs.size() > 9) ? pfvecs[9].dphi : -50;
    Jet_pf_9_puppiwt = (pfvecs.size() > 9) ? pfvecs[9].puppiwt : -50;
    Jet_pf_9_dxy = (pfvecs.size() > 9) ? pfvecs[9].dxy : -50;
    Jet_pf_9_dz = (pfvecs.size() > 9) ? pfvecs[9].dz : -50;
    Jet_pf_10_ptfrac = (pfvecs.size() > 10) ? pfvecs[10].ptfrac : -50;
    Jet_pf_10_deta = (pfvecs.size() > 10) ? pfvecs[10].deta : -50;
    Jet_pf_10_dphi = (pfvecs.size() > 10) ? pfvecs[10].dphi : -50;
    Jet_pf_10_puppiwt = (pfvecs.size() > 10) ? pfvecs[10].puppiwt : -50;
    Jet_pf_10_dxy = (pfvecs.size() > 10) ? pfvecs[10].dxy : -50;
    Jet_pf_10_dz = (pfvecs.size() > 10) ? pfvecs[10].dz : -50;
    Jet_pf_11_ptfrac = (pfvecs.size() > 11) ? pfvecs[11].ptfrac : -50;
    Jet_pf_11_deta = (pfvecs.size() > 11) ? pfvecs[11].deta : -50;
    Jet_pf_11_dphi = (pfvecs.size() > 11) ? pfvecs[11].dphi : -50;
    Jet_pf_11_puppiwt = (pfvecs.size() > 11) ? pfvecs[11].puppiwt : -50;
    Jet_pf_11_dxy = (pfvecs.size() > 11) ? pfvecs[11].dxy : -50;
    Jet_pf_11_dz = (pfvecs.size() > 11) ? pfvecs[11].dz : -50;
    Jet_pf_12_ptfrac = (pfvecs.size() > 12) ? pfvecs[12].ptfrac : -50;
    Jet_pf_12_deta = (pfvecs.size() > 12) ? pfvecs[12].deta : -50;
    Jet_pf_12_dphi = (pfvecs.size() > 12) ? pfvecs[12].dphi : -50;
    Jet_pf_12_puppiwt = (pfvecs.size() > 12) ? pfvecs[12].puppiwt : -50;
    Jet_pf_12_dxy = (pfvecs.size() > 12) ? pfvecs[12].dxy : -50;
    Jet_pf_12_dz = (pfvecs.size() > 12) ? pfvecs[12].dz : -50;
    Jet_pf_13_ptfrac = (pfvecs.size() > 13) ? pfvecs[13].ptfrac : -50;
    Jet_pf_13_deta = (pfvecs.size() > 13) ? pfvecs[13].deta : -50;
    Jet_pf_13_dphi = (pfvecs.size() > 13) ? pfvecs[13].dphi : -50;
    Jet_pf_13_puppiwt = (pfvecs.size() > 13) ? pfvecs[13].puppiwt : -50;
    Jet_pf_13_dxy = (pfvecs.size() > 13) ? pfvecs[13].dxy : -50;
    Jet_pf_13_dz = (pfvecs.size() > 13) ? pfvecs[13].dz : -50;
    Jet_pf_14_ptfrac = (pfvecs.size() > 14) ? pfvecs[14].ptfrac : -50;
    Jet_pf_14_deta = (pfvecs.size() > 14) ? pfvecs[14].deta : -50;
    Jet_pf_14_dphi = (pfvecs.size() > 14) ? pfvecs[14].dphi : -50;
    Jet_pf_14_puppiwt = (pfvecs.size() > 14) ? pfvecs[14].puppiwt : -50;
    Jet_pf_14_dxy = (pfvecs.size() > 14) ? pfvecs[14].dxy : -50;
    Jet_pf_14_dz = (pfvecs.size() > 14) ? pfvecs[14].dz : -50;
    Jet_pf_15_ptfrac = (pfvecs.size() > 15) ? pfvecs[15].ptfrac : -50;
    Jet_pf_15_deta = (pfvecs.size() > 15) ? pfvecs[15].deta : -50;
    Jet_pf_15_dphi = (pfvecs.size() > 15) ? pfvecs[15].dphi : -50;
    Jet_pf_15_puppiwt = (pfvecs.size() > 15) ? pfvecs[15].puppiwt : -50;
    Jet_pf_15_dxy = (pfvecs.size() > 15) ? pfvecs[15].dxy : -50;
    Jet_pf_15_dz = (pfvecs.size() > 15) ? pfvecs[15].dz : -50;
    Jet_pf_16_ptfrac = (pfvecs.size() > 16) ? pfvecs[16].ptfrac : -50;
    Jet_pf_16_deta = (pfvecs.size() > 16) ? pfvecs[16].deta : -50;
    Jet_pf_16_dphi = (pfvecs.size() > 16) ? pfvecs[16].dphi : -50;
    Jet_pf_16_puppiwt = (pfvecs.size() > 16) ? pfvecs[16].puppiwt : -50;
    Jet_pf_16_dxy = (pfvecs.size() > 16) ? pfvecs[16].dxy : -50;
    Jet_pf_16_dz = (pfvecs.size() > 16) ? pfvecs[16].dz : -50;
    Jet_pf_17_ptfrac = (pfvecs.size() > 17) ? pfvecs[17].ptfrac : -50;
    Jet_pf_17_deta = (pfvecs.size() > 17) ? pfvecs[17].deta : -50;
    Jet_pf_17_dphi = (pfvecs.size() > 17) ? pfvecs[17].dphi : -50;
    Jet_pf_17_puppiwt = (pfvecs.size() > 17) ? pfvecs[17].puppiwt : -50;
    Jet_pf_17_dxy = (pfvecs.size() > 17) ? pfvecs[17].dxy : -50;
    Jet_pf_17_dz = (pfvecs.size() > 17) ? pfvecs[17].dz : -50;
    Jet_pf_18_ptfrac = (pfvecs.size() > 18) ? pfvecs[18].ptfrac : -50;
    Jet_pf_18_deta = (pfvecs.size() > 18) ? pfvecs[18].deta : -50;
    Jet_pf_18_dphi = (pfvecs.size() > 18) ? pfvecs[18].dphi : -50;
    Jet_pf_18_puppiwt = (pfvecs.size() > 18) ? pfvecs[18].puppiwt : -50;
    Jet_pf_18_dxy = (pfvecs.size() > 18) ? pfvecs[18].dxy : -50;
    Jet_pf_18_dz = (pfvecs.size() > 18) ? pfvecs[18].dz : -50;
    Jet_pf_19_ptfrac = (pfvecs.size() > 19) ? pfvecs[19].ptfrac : -50;
    Jet_pf_19_deta = (pfvecs.size() > 19) ? pfvecs[19].deta : -50;
    Jet_pf_19_dphi = (pfvecs.size() > 19) ? pfvecs[19].dphi : -50;
    Jet_pf_19_puppiwt = (pfvecs.size() > 19) ? pfvecs[19].puppiwt : -50;
    Jet_pf_19_dxy = (pfvecs.size() > 19) ? pfvecs[19].dxy : -50;
    Jet_pf_19_dz = (pfvecs.size() > 19) ? pfvecs[19].dz : -50;
    Jet_pf_0_q = (pfvecs.size() > 0) ? pfvecs[0].q : -10;
    Jet_pf_1_q = (pfvecs.size() > 1) ? pfvecs[1].q : -10;
    Jet_pf_2_q = (pfvecs.size() > 2) ? pfvecs[2].q : -10;
    Jet_pf_3_q = (pfvecs.size() > 3) ? pfvecs[3].q : -10;
    Jet_pf_4_q = (pfvecs.size() > 4) ? pfvecs[4].q : -10;
    Jet_pf_5_q = (pfvecs.size() > 5) ? pfvecs[5].q : -10;
    Jet_pf_6_q = (pfvecs.size() > 6) ? pfvecs[6].q : -10;
    Jet_pf_7_q = (pfvecs.size() > 7) ? pfvecs[7].q : -10;
    Jet_pf_8_q = (pfvecs.size() > 8) ? pfvecs[8].q : -10;
    Jet_pf_9_q = (pfvecs.size() > 9) ? pfvecs[9].q : -10;
    Jet_pf_10_q = (pfvecs.size() > 10) ? pfvecs[10].q : -10;
    Jet_pf_11_q = (pfvecs.size() > 11) ? pfvecs[11].q : -10;
    Jet_pf_12_q = (pfvecs.size() > 12) ? pfvecs[12].q : -10;
    Jet_pf_13_q = (pfvecs.size() > 13) ? pfvecs[13].q : -10;
    Jet_pf_14_q = (pfvecs.size() > 14) ? pfvecs[14].q : -10;
    Jet_pf_15_q = (pfvecs.size() > 15) ? pfvecs[15].q : -10;
    Jet_pf_16_q = (pfvecs.size() > 16) ? pfvecs[16].q : -10;
    Jet_pf_17_q = (pfvecs.size() > 17) ? pfvecs[17].q : -10;
    Jet_pf_18_q = (pfvecs.size() > 18) ? pfvecs[18].q : -10;
    Jet_pf_19_q = (pfvecs.size() > 19) ? pfvecs[19].q : -10;
    Jet_pf_0_is_ele = (pfvecs.size() > 0) ? pfvecs[0].is_ele : 0;
    Jet_pf_0_is_muon = (pfvecs.size() > 0) ? pfvecs[0].is_muon : 0;
    Jet_pf_0_is_photon = (pfvecs.size() > 0) ? pfvecs[0].is_photon : 0;
    Jet_pf_0_is_nhadron = (pfvecs.size() > 0) ? pfvecs[0].is_nhadron : 0;
    Jet_pf_0_is_chhadron = (pfvecs.size() > 0) ? pfvecs[0].is_chhadron : 0;
    Jet_pf_1_is_ele = (pfvecs.size() > 1) ? pfvecs[1].is_ele : 0;
    Jet_pf_1_is_muon = (pfvecs.size() > 1) ? pfvecs[1].is_muon : 0;
    Jet_pf_1_is_photon = (pfvecs.size() > 1) ? pfvecs[1].is_photon : 0;
    Jet_pf_1_is_nhadron = (pfvecs.size() > 1) ? pfvecs[1].is_nhadron : 0;
    Jet_pf_1_is_chhadron = (pfvecs.size() > 1) ? pfvecs[1].is_chhadron : 0;
    Jet_pf_2_is_ele = (pfvecs.size() > 2) ? pfvecs[2].is_ele : 0;
    Jet_pf_2_is_muon = (pfvecs.size() > 2) ? pfvecs[2].is_muon : 0;
    Jet_pf_2_is_photon = (pfvecs.size() > 2) ? pfvecs[2].is_photon : 0;
    Jet_pf_2_is_nhadron = (pfvecs.size() > 2) ? pfvecs[2].is_nhadron : 0;
    Jet_pf_2_is_chhadron = (pfvecs.size() > 2) ? pfvecs[2].is_chhadron : 0;
    Jet_pf_3_is_ele = (pfvecs.size() > 3) ? pfvecs[3].is_ele : 0;
    Jet_pf_3_is_muon = (pfvecs.size() > 3) ? pfvecs[3].is_muon : 0;
    Jet_pf_3_is_photon = (pfvecs.size() > 3) ? pfvecs[3].is_photon : 0;
    Jet_pf_3_is_nhadron = (pfvecs.size() > 3) ? pfvecs[3].is_nhadron : 0;
    Jet_pf_3_is_chhadron = (pfvecs.size() > 3) ? pfvecs[3].is_chhadron : 0;
    Jet_pf_4_is_ele = (pfvecs.size() > 4) ? pfvecs[4].is_ele : 0;
    Jet_pf_4_is_muon = (pfvecs.size() > 4) ? pfvecs[4].is_muon : 0;
    Jet_pf_4_is_photon = (pfvecs.size() > 4) ? pfvecs[4].is_photon : 0;
    Jet_pf_4_is_nhadron = (pfvecs.size() > 4) ? pfvecs[4].is_nhadron : 0;
    Jet_pf_4_is_chhadron = (pfvecs.size() > 4) ? pfvecs[4].is_chhadron : 0;
    Jet_pf_5_is_ele = (pfvecs.size() > 5) ? pfvecs[5].is_ele : 0;
    Jet_pf_5_is_muon = (pfvecs.size() > 5) ? pfvecs[5].is_muon : 0;
    Jet_pf_5_is_photon = (pfvecs.size() > 5) ? pfvecs[5].is_photon : 0;
    Jet_pf_5_is_nhadron = (pfvecs.size() > 5) ? pfvecs[5].is_nhadron : 0;
    Jet_pf_5_is_chhadron = (pfvecs.size() > 5) ? pfvecs[5].is_chhadron : 0;
    Jet_pf_6_is_ele = (pfvecs.size() > 6) ? pfvecs[6].is_ele : 0;
    Jet_pf_6_is_muon = (pfvecs.size() > 6) ? pfvecs[6].is_muon : 0;
    Jet_pf_6_is_photon = (pfvecs.size() > 6) ? pfvecs[6].is_photon : 0;
    Jet_pf_6_is_nhadron = (pfvecs.size() > 6) ? pfvecs[6].is_nhadron : 0;
    Jet_pf_6_is_chhadron = (pfvecs.size() > 6) ? pfvecs[6].is_chhadron : 0;
    Jet_pf_7_is_ele = (pfvecs.size() > 7) ? pfvecs[7].is_ele : 0;
    Jet_pf_7_is_muon = (pfvecs.size() > 7) ? pfvecs[7].is_muon : 0;
    Jet_pf_7_is_photon = (pfvecs.size() > 7) ? pfvecs[7].is_photon : 0;
    Jet_pf_7_is_nhadron = (pfvecs.size() > 7) ? pfvecs[7].is_nhadron : 0;
    Jet_pf_7_is_chhadron = (pfvecs.size() > 7) ? pfvecs[7].is_chhadron : 0;
    Jet_pf_8_is_ele = (pfvecs.size() > 8) ? pfvecs[8].is_ele : 0;
    Jet_pf_8_is_muon = (pfvecs.size() > 8) ? pfvecs[8].is_muon : 0;
    Jet_pf_8_is_photon = (pfvecs.size() > 8) ? pfvecs[8].is_photon : 0;
    Jet_pf_8_is_nhadron = (pfvecs.size() > 8) ? pfvecs[8].is_nhadron : 0;
    Jet_pf_8_is_chhadron = (pfvecs.size() > 8) ? pfvecs[8].is_chhadron : 0;
    Jet_pf_9_is_ele = (pfvecs.size() > 9) ? pfvecs[9].is_ele : 0;
    Jet_pf_9_is_muon = (pfvecs.size() > 9) ? pfvecs[9].is_muon : 0;
    Jet_pf_9_is_photon = (pfvecs.size() > 9) ? pfvecs[9].is_photon : 0;
    Jet_pf_9_is_nhadron = (pfvecs.size() > 9) ? pfvecs[9].is_nhadron : 0;
    Jet_pf_9_is_chhadron = (pfvecs.size() > 9) ? pfvecs[9].is_chhadron : 0;
    Jet_pf_10_is_ele = (pfvecs.size() > 10) ? pfvecs[10].is_ele : 0;
    Jet_pf_10_is_muon = (pfvecs.size() > 10) ? pfvecs[10].is_muon : 0;
    Jet_pf_10_is_photon = (pfvecs.size() > 10) ? pfvecs[10].is_photon : 0;
    Jet_pf_10_is_nhadron = (pfvecs.size() > 10) ? pfvecs[10].is_nhadron : 0;
    Jet_pf_10_is_chhadron = (pfvecs.size() > 10) ? pfvecs[10].is_chhadron : 0;
    Jet_pf_11_is_ele = (pfvecs.size() > 11) ? pfvecs[11].is_ele : 0;
    Jet_pf_11_is_muon = (pfvecs.size() > 11) ? pfvecs[11].is_muon : 0;
    Jet_pf_11_is_photon = (pfvecs.size() > 11) ? pfvecs[11].is_photon : 0;
    Jet_pf_11_is_nhadron = (pfvecs.size() > 11) ? pfvecs[11].is_nhadron : 0;
    Jet_pf_11_is_chhadron = (pfvecs.size() > 11) ? pfvecs[11].is_chhadron : 0;
    Jet_pf_12_is_ele = (pfvecs.size() > 12) ? pfvecs[12].is_ele : 0;
    Jet_pf_12_is_muon = (pfvecs.size() > 12) ? pfvecs[12].is_muon : 0;
    Jet_pf_12_is_photon = (pfvecs.size() > 12) ? pfvecs[12].is_photon : 0;
    Jet_pf_12_is_nhadron = (pfvecs.size() > 12) ? pfvecs[12].is_nhadron : 0;
    Jet_pf_12_is_chhadron = (pfvecs.size() > 12) ? pfvecs[12].is_chhadron : 0;
    Jet_pf_13_is_ele = (pfvecs.size() > 13) ? pfvecs[13].is_ele : 0;
    Jet_pf_13_is_muon = (pfvecs.size() > 13) ? pfvecs[13].is_muon : 0;
    Jet_pf_13_is_photon = (pfvecs.size() > 13) ? pfvecs[13].is_photon : 0;
    Jet_pf_13_is_nhadron = (pfvecs.size() > 13) ? pfvecs[13].is_nhadron : 0;
    Jet_pf_13_is_chhadron = (pfvecs.size() > 13) ? pfvecs[13].is_chhadron : 0;
    Jet_pf_14_is_ele = (pfvecs.size() > 14) ? pfvecs[14].is_ele : 0;
    Jet_pf_14_is_muon = (pfvecs.size() > 14) ? pfvecs[14].is_muon : 0;
    Jet_pf_14_is_photon = (pfvecs.size() > 14) ? pfvecs[14].is_photon : 0;
    Jet_pf_14_is_nhadron = (pfvecs.size() > 14) ? pfvecs[14].is_nhadron : 0;
    Jet_pf_14_is_chhadron = (pfvecs.size() > 14) ? pfvecs[14].is_chhadron : 0;
    Jet_pf_15_is_ele = (pfvecs.size() > 15) ? pfvecs[15].is_ele : 0;
    Jet_pf_15_is_muon = (pfvecs.size() > 15) ? pfvecs[15].is_muon : 0;
    Jet_pf_15_is_photon = (pfvecs.size() > 15) ? pfvecs[15].is_photon : 0;
    Jet_pf_15_is_nhadron = (pfvecs.size() > 15) ? pfvecs[15].is_nhadron : 0;
    Jet_pf_15_is_chhadron = (pfvecs.size() > 15) ? pfvecs[15].is_chhadron : 0;
    Jet_pf_16_is_ele = (pfvecs.size() > 16) ? pfvecs[16].is_ele : 0;
    Jet_pf_16_is_muon = (pfvecs.size() > 16) ? pfvecs[16].is_muon : 0;
    Jet_pf_16_is_photon = (pfvecs.size() > 16) ? pfvecs[16].is_photon : 0;
    Jet_pf_16_is_nhadron = (pfvecs.size() > 16) ? pfvecs[16].is_nhadron : 0;
    Jet_pf_16_is_chhadron = (pfvecs.size() > 16) ? pfvecs[16].is_chhadron : 0;
    Jet_pf_17_is_ele = (pfvecs.size() > 17) ? pfvecs[17].is_ele : 0;
    Jet_pf_17_is_muon = (pfvecs.size() > 17) ? pfvecs[17].is_muon : 0;
    Jet_pf_17_is_photon = (pfvecs.size() > 17) ? pfvecs[17].is_photon : 0;
    Jet_pf_17_is_nhadron = (pfvecs.size() > 17) ? pfvecs[17].is_nhadron : 0;
    Jet_pf_17_is_chhadron = (pfvecs.size() > 17) ? pfvecs[17].is_chhadron : 0;
    Jet_pf_18_is_ele = (pfvecs.size() > 18) ? pfvecs[18].is_ele : 0;
    Jet_pf_18_is_muon = (pfvecs.size() > 18) ? pfvecs[18].is_muon : 0;
    Jet_pf_18_is_photon = (pfvecs.size() > 18) ? pfvecs[18].is_photon : 0;
    Jet_pf_18_is_nhadron = (pfvecs.size() > 18) ? pfvecs[18].is_nhadron : 0;
    Jet_pf_18_is_chhadron = (pfvecs.size() > 18) ? pfvecs[18].is_chhadron : 0;
    Jet_pf_19_is_ele = (pfvecs.size() > 19) ? pfvecs[19].is_ele : 0;
    Jet_pf_19_is_muon = (pfvecs.size() > 19) ? pfvecs[19].is_muon : 0;
    Jet_pf_19_is_photon = (pfvecs.size() > 19) ? pfvecs[19].is_photon : 0;
    Jet_pf_19_is_nhadron = (pfvecs.size() > 19) ? pfvecs[19].is_nhadron : 0;
    Jet_pf_19_is_chhadron = (pfvecs.size() > 19) ? pfvecs[19].is_chhadron : 0;
    Jet_pf_0_transformed_px = (pfvecs.size() > 0) ? pfvecs[0].transformed.Px() : 0;
    Jet_pf_0_transformed_py = (pfvecs.size() > 0) ? pfvecs[0].transformed.Py() : 0;
    Jet_pf_0_transformed_pz = (pfvecs.size() > 0) ? pfvecs[0].transformed.Pz() : 0;
    Jet_pf_1_transformed_px = (pfvecs.size() > 1) ? pfvecs[1].transformed.Px() : 0;
    Jet_pf_1_transformed_py = (pfvecs.size() > 1) ? pfvecs[1].transformed.Py() : 0;
    Jet_pf_1_transformed_pz = (pfvecs.size() > 1) ? pfvecs[1].transformed.Pz() : 0;
    Jet_pf_2_transformed_px = (pfvecs.size() > 2) ? pfvecs[2].transformed.Px() : 0;
    Jet_pf_2_transformed_py = (pfvecs.size() > 2) ? pfvecs[2].transformed.Py() : 0;
    Jet_pf_2_transformed_pz = (pfvecs.size() > 2) ? pfvecs[2].transformed.Pz() : 0;
    Jet_pf_3_transformed_px = (pfvecs.size() > 3) ? pfvecs[3].transformed.Px() : 0;
    Jet_pf_3_transformed_py = (pfvecs.size() > 3) ? pfvecs[3].transformed.Py() : 0;
    Jet_pf_3_transformed_pz = (pfvecs.size() > 3) ? pfvecs[3].transformed.Pz() : 0;
    Jet_pf_4_transformed_px = (pfvecs.size() > 4) ? pfvecs[4].transformed.Px() : 0;
    Jet_pf_4_transformed_py = (pfvecs.size() > 4) ? pfvecs[4].transformed.Py() : 0;
    Jet_pf_4_transformed_pz = (pfvecs.size() > 4) ? pfvecs[4].transformed.Pz() : 0;
    Jet_pf_5_transformed_px = (pfvecs.size() > 5) ? pfvecs[5].transformed.Px() : 0;
    Jet_pf_5_transformed_py = (pfvecs.size() > 5) ? pfvecs[5].transformed.Py() : 0;
    Jet_pf_5_transformed_pz = (pfvecs.size() > 5) ? pfvecs[5].transformed.Pz() : 0;
    Jet_pf_6_transformed_px = (pfvecs.size() > 6) ? pfvecs[6].transformed.Px() : 0;
    Jet_pf_6_transformed_py = (pfvecs.size() > 6) ? pfvecs[6].transformed.Py() : 0;
    Jet_pf_6_transformed_pz = (pfvecs.size() > 6) ? pfvecs[6].transformed.Pz() : 0;
    Jet_pf_7_transformed_px = (pfvecs.size() > 7) ? pfvecs[7].transformed.Px() : 0;
    Jet_pf_7_transformed_py = (pfvecs.size() > 7) ? pfvecs[7].transformed.Py() : 0;
    Jet_pf_7_transformed_pz = (pfvecs.size() > 7) ? pfvecs[7].transformed.Pz() : 0;
    Jet_pf_8_transformed_px = (pfvecs.size() > 8) ? pfvecs[8].transformed.Px() : 0;
    Jet_pf_8_transformed_py = (pfvecs.size() > 8) ? pfvecs[8].transformed.Py() : 0;
    Jet_pf_8_transformed_pz = (pfvecs.size() > 8) ? pfvecs[8].transformed.Pz() : 0;
    Jet_pf_9_transformed_px = (pfvecs.size() > 9) ? pfvecs[9].transformed.Px() : 0;
    Jet_pf_9_transformed_py = (pfvecs.size() > 9) ? pfvecs[9].transformed.Py() : 0;
    Jet_pf_9_transformed_pz = (pfvecs.size() > 9) ? pfvecs[9].transformed.Pz() : 0;
    Jet_pf_10_transformed_px = (pfvecs.size() > 10) ? pfvecs[10].transformed.Px() : 0;
    Jet_pf_10_transformed_py = (pfvecs.size() > 10) ? pfvecs[10].transformed.Py() : 0;
    Jet_pf_10_transformed_pz = (pfvecs.size() > 10) ? pfvecs[10].transformed.Pz() : 0;
    Jet_pf_11_transformed_px = (pfvecs.size() > 11) ? pfvecs[11].transformed.Px() : 0;
    Jet_pf_11_transformed_py = (pfvecs.size() > 11) ? pfvecs[11].transformed.Py() : 0;
    Jet_pf_11_transformed_pz = (pfvecs.size() > 11) ? pfvecs[11].transformed.Pz() : 0;
    Jet_pf_12_transformed_px = (pfvecs.size() > 12) ? pfvecs[12].transformed.Px() : 0;
    Jet_pf_12_transformed_py = (pfvecs.size() > 12) ? pfvecs[12].transformed.Py() : 0;
    Jet_pf_12_transformed_pz = (pfvecs.size() > 12) ? pfvecs[12].transformed.Pz() : 0;
    Jet_pf_13_transformed_px = (pfvecs.size() > 13) ? pfvecs[13].transformed.Px() : 0;
    Jet_pf_13_transformed_py = (pfvecs.size() > 13) ? pfvecs[13].transformed.Py() : 0;
    Jet_pf_13_transformed_pz = (pfvecs.size() > 13) ? pfvecs[13].transformed.Pz() : 0;
    Jet_pf_14_transformed_px = (pfvecs.size() > 14) ? pfvecs[14].transformed.Px() : 0;
    Jet_pf_14_transformed_py = (pfvecs.size() > 14) ? pfvecs[14].transformed.Py() : 0;
    Jet_pf_14_transformed_pz = (pfvecs.size() > 14) ? pfvecs[14].transformed.Pz() : 0;
    Jet_pf_15_transformed_px = (pfvecs.size() > 15) ? pfvecs[15].transformed.Px() : 0;
    Jet_pf_15_transformed_py = (pfvecs.size() > 15) ? pfvecs[15].transformed.Py() : 0;
    Jet_pf_15_transformed_pz = (pfvecs.size() > 15) ? pfvecs[15].transformed.Pz() : 0;
    Jet_pf_16_transformed_px = (pfvecs.size() > 16) ? pfvecs[16].transformed.Px() : 0;
    Jet_pf_16_transformed_py = (pfvecs.size() > 16) ? pfvecs[16].transformed.Py() : 0;
    Jet_pf_16_transformed_pz = (pfvecs.size() > 16) ? pfvecs[16].transformed.Pz() : 0;
    Jet_pf_17_transformed_px = (pfvecs.size() > 17) ? pfvecs[17].transformed.Px() : 0;
    Jet_pf_17_transformed_py = (pfvecs.size() > 17) ? pfvecs[17].transformed.Py() : 0;
    Jet_pf_17_transformed_pz = (pfvecs.size() > 17) ? pfvecs[17].transformed.Pz() : 0;
    Jet_pf_18_transformed_px = (pfvecs.size() > 18) ? pfvecs[18].transformed.Px() : 0;
    Jet_pf_18_transformed_py = (pfvecs.size() > 18) ? pfvecs[18].transformed.Py() : 0;
    Jet_pf_18_transformed_pz = (pfvecs.size() > 18) ? pfvecs[18].transformed.Pz() : 0;
    Jet_pf_19_transformed_px = (pfvecs.size() > 19) ? pfvecs[19].transformed.Px() : 0;
    Jet_pf_19_transformed_py = (pfvecs.size() > 19) ? pfvecs[19].transformed.Py() : 0;
    Jet_pf_19_transformed_pz = (pfvecs.size() > 19) ? pfvecs[19].transformed.Pz() : 0;
    break;
  default:
    throw;
  }
}

#endif
