#ifndef CROMBIE_REGFILE_H
#define CROMBIE_REGFILE_H

#include <string>
#include <vector>
#include "TObject.h"
#include "TFile.h"
#include "TTree.h"
#include "lazytf.h"
#include "genjet.h"
#include "regression.h"
#include "TVector2.h"
#include "tensorflow/core/public/session.h"
#include <memory>

void check_tf (const tensorflow::Status& status) {
  if (not status.ok()) {
    std::cerr << status.error_message() << std::endl;
    throw;
  }
}

class regfile {

 public:
  regfile(const char* outfile_name, const char* name = "events");
  ~regfile() { write(t); f->Close(); }

  Float_t Jet_btagCMVA;
  Float_t Jet_btagDeepB;
  Float_t Jet_btagDeepC;
  Float_t Jet_chEmEF;
  Float_t Jet_chHEF;
  Float_t Jet_e;
  Float_t Jet_energyRing_dR0_ch;
  Float_t Jet_energyRing_dR0_ch_Jet_rawEnergy;
  Float_t Jet_energyRing_dR0_em;
  Float_t Jet_energyRing_dR0_em_Jet_rawEnergy;
  Float_t Jet_energyRing_dR0_mu;
  Float_t Jet_energyRing_dR0_mu_Jet_rawEnergy;
  Float_t Jet_energyRing_dR0_neut;
  Float_t Jet_energyRing_dR0_neut_Jet_rawEnergy;
  Float_t Jet_energyRing_dR1_ch;
  Float_t Jet_energyRing_dR1_ch_Jet_rawEnergy;
  Float_t Jet_energyRing_dR1_em;
  Float_t Jet_energyRing_dR1_em_Jet_rawEnergy;
  Float_t Jet_energyRing_dR1_mu;
  Float_t Jet_energyRing_dR1_mu_Jet_rawEnergy;
  Float_t Jet_energyRing_dR1_neut;
  Float_t Jet_energyRing_dR1_neut_Jet_rawEnergy;
  Float_t Jet_energyRing_dR2_ch;
  Float_t Jet_energyRing_dR2_ch_Jet_rawEnergy;
  Float_t Jet_energyRing_dR2_em;
  Float_t Jet_energyRing_dR2_em_Jet_rawEnergy;
  Float_t Jet_energyRing_dR2_mu;
  Float_t Jet_energyRing_dR2_mu_Jet_rawEnergy;
  Float_t Jet_energyRing_dR2_neut;
  Float_t Jet_energyRing_dR2_neut_Jet_rawEnergy;
  Float_t Jet_energyRing_dR3_ch;
  Float_t Jet_energyRing_dR3_ch_Jet_rawEnergy;
  Float_t Jet_energyRing_dR3_em;
  Float_t Jet_energyRing_dR3_em_Jet_rawEnergy;
  Float_t Jet_energyRing_dR3_mu;
  Float_t Jet_energyRing_dR3_mu_Jet_rawEnergy;
  Float_t Jet_energyRing_dR3_neut;
  Float_t Jet_energyRing_dR3_neut_Jet_rawEnergy;
  Float_t Jet_energyRing_dR4_ch;
  Float_t Jet_energyRing_dR4_ch_Jet_rawEnergy;
  Float_t Jet_energyRing_dR4_em;
  Float_t Jet_energyRing_dR4_em_Jet_rawEnergy;
  Float_t Jet_energyRing_dR4_mu;
  Float_t Jet_energyRing_dR4_mu_Jet_rawEnergy;
  Float_t Jet_energyRing_dR4_neut;
  Float_t Jet_energyRing_dR4_neut_Jet_rawEnergy;
  Float_t Jet_energyRing_dR5_ch;
  Float_t Jet_energyRing_dR5_ch_Jet_rawEnergy;
  Float_t Jet_energyRing_dR5_em;
  Float_t Jet_energyRing_dR5_em_Jet_rawEnergy;
  Float_t Jet_energyRing_dR5_mu;
  Float_t Jet_energyRing_dR5_mu_Jet_rawEnergy;
  Float_t Jet_energyRing_dR5_neut;
  Float_t Jet_energyRing_dR5_neut_Jet_rawEnergy;
  Float_t Jet_eta;
  Float_t Jet_leadTrackPt;
  Float_t Jet_leptonDeltaR;
  Int_t Jet_leptonPdgId;
  Float_t Jet_leptonPt;
  Float_t Jet_leptonPtRel;
  Float_t Jet_leptonPtRelInv;
  Float_t Jet_mass;
  Float_t Jet_mcFlavour;
  Float_t Jet_mcPt;
  Float_t Jet_met_dPhi;
  Float_t Jet_mt;
  Float_t Jet_neEmEF;
  Float_t Jet_neHEF;
  UShort_t Jet_numDaughters_pt03;
  UShort_t Jet_numberOfDaughters;
  Float_t Jet_pf_0_deta;
  Float_t Jet_pf_0_dphi;
  Float_t Jet_pf_0_dxy;
  Float_t Jet_pf_0_dz;
  Int_t Jet_pf_0_pdgid;
  Float_t Jet_pf_0_ptfrac;
  Float_t Jet_pf_0_puppiwt;
  Float_t Jet_pf_1_deta;
  Float_t Jet_pf_1_dphi;
  Float_t Jet_pf_1_dxy;
  Float_t Jet_pf_1_dz;
  Int_t Jet_pf_1_pdgid;
  Float_t Jet_pf_1_ptfrac;
  Float_t Jet_pf_1_puppiwt;
  Float_t Jet_pf_2_deta;
  Float_t Jet_pf_2_dphi;
  Float_t Jet_pf_2_dxy;
  Float_t Jet_pf_2_dz;
  Int_t Jet_pf_2_pdgid;
  Float_t Jet_pf_2_ptfrac;
  Float_t Jet_pf_2_puppiwt;
  Float_t Jet_pf_3_deta;
  Float_t Jet_pf_3_dphi;
  Float_t Jet_pf_3_dxy;
  Float_t Jet_pf_3_dz;
  Int_t Jet_pf_3_pdgid;
  Float_t Jet_pf_3_ptfrac;
  Float_t Jet_pf_3_puppiwt;
  Float_t Jet_pf_4_deta;
  Float_t Jet_pf_4_dphi;
  Float_t Jet_pf_4_dxy;
  Float_t Jet_pf_4_dz;
  Int_t Jet_pf_4_pdgid;
  Float_t Jet_pf_4_ptfrac;
  Float_t Jet_pf_4_puppiwt;
  Float_t Jet_pf_5_deta;
  Float_t Jet_pf_5_dphi;
  Float_t Jet_pf_5_dxy;
  Float_t Jet_pf_5_dz;
  Int_t Jet_pf_5_pdgid;
  Float_t Jet_pf_5_ptfrac;
  Float_t Jet_pf_5_puppiwt;
  Float_t Jet_pf_6_deta;
  Float_t Jet_pf_6_dphi;
  Float_t Jet_pf_6_dxy;
  Float_t Jet_pf_6_dz;
  Int_t Jet_pf_6_pdgid;
  Float_t Jet_pf_6_ptfrac;
  Float_t Jet_pf_6_puppiwt;
  Float_t Jet_pf_7_deta;
  Float_t Jet_pf_7_dphi;
  Float_t Jet_pf_7_dxy;
  Float_t Jet_pf_7_dz;
  Int_t Jet_pf_7_pdgid;
  Float_t Jet_pf_7_ptfrac;
  Float_t Jet_pf_7_puppiwt;
  Float_t Jet_pf_8_deta;
  Float_t Jet_pf_8_dphi;
  Float_t Jet_pf_8_dxy;
  Float_t Jet_pf_8_dz;
  Int_t Jet_pf_8_pdgid;
  Float_t Jet_pf_8_ptfrac;
  Float_t Jet_pf_8_puppiwt;
  Float_t Jet_pf_9_deta;
  Float_t Jet_pf_9_dphi;
  Float_t Jet_pf_9_dxy;
  Float_t Jet_pf_9_dz;
  Int_t Jet_pf_9_pdgid;
  Float_t Jet_pf_9_ptfrac;
  Float_t Jet_pf_9_puppiwt;
  Float_t Jet_phi;
  Float_t Jet_pt;
  Float_t Jet_ptd;
  Float_t Jet_puId;
  Float_t Jet_raw;
  Float_t Jet_rawEnergy;
  Float_t Jet_rawFactor;
  Float_t Jet_tf_ptratio;
  Float_t Jet_tf_ptratio_nopf;
  Float_t Jet_vtx3dL;
  Float_t Jet_vtx3deL;
  Float_t Jet_vtxMass;
  UShort_t Jet_vtxNtrk;
  Float_t Jet_vtxPt;
  Float_t Jet_withPtd;
  ULong64_t event;
  Float_t genWeight;
  Float_t isEle;
  Float_t isMu;
  Float_t isOther;
  ULong64_t luminosityBlock;
  Float_t met_phi;
  Float_t met_pt;
  Float_t nPVs;
  Float_t nPVs_good;
  Float_t rho;
  UInt_t run;

  void reset(const panda::Event& e);
  void fill();
  void write(TObject* obj) { f->WriteTObject(obj, obj->GetName()); }
  
  enum class jet {
    Jet
  };
  template <typename G> void set_jet(const jet base, const panda::Jet& jet, const gennujet::GenNuVec& withnu, const G gen);

 private:
  TFile* f;
  TTree* t;

  std::unique_ptr<tensorflow::Session> v2018_dan_session {tensorflow::NewSession({})};
  std::unique_ptr<tensorflow::Session> v2018_dan_noPFs_session {tensorflow::NewSession({})};
};

regfile::regfile(const char* outfile_name, const char* name)
: f {new TFile(outfile_name, "CREATE", "", 1)},
  t {new TTree(name, name)}
{
  t->Branch("Jet_btagCMVA", &Jet_btagCMVA, "Jet_btagCMVA/F");
  t->Branch("Jet_btagDeepB", &Jet_btagDeepB, "Jet_btagDeepB/F");
  t->Branch("Jet_btagDeepC", &Jet_btagDeepC, "Jet_btagDeepC/F");
  t->Branch("Jet_chEmEF", &Jet_chEmEF, "Jet_chEmEF/F");
  t->Branch("Jet_chHEF", &Jet_chHEF, "Jet_chHEF/F");
  t->Branch("Jet_e", &Jet_e, "Jet_e/F");
  t->Branch("Jet_energyRing_dR0_ch", &Jet_energyRing_dR0_ch, "Jet_energyRing_dR0_ch/F");
  t->Branch("Jet_energyRing_dR0_ch_Jet_rawEnergy", &Jet_energyRing_dR0_ch_Jet_rawEnergy, "Jet_energyRing_dR0_ch_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR0_em", &Jet_energyRing_dR0_em, "Jet_energyRing_dR0_em/F");
  t->Branch("Jet_energyRing_dR0_em_Jet_rawEnergy", &Jet_energyRing_dR0_em_Jet_rawEnergy, "Jet_energyRing_dR0_em_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR0_mu", &Jet_energyRing_dR0_mu, "Jet_energyRing_dR0_mu/F");
  t->Branch("Jet_energyRing_dR0_mu_Jet_rawEnergy", &Jet_energyRing_dR0_mu_Jet_rawEnergy, "Jet_energyRing_dR0_mu_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR0_neut", &Jet_energyRing_dR0_neut, "Jet_energyRing_dR0_neut/F");
  t->Branch("Jet_energyRing_dR0_neut_Jet_rawEnergy", &Jet_energyRing_dR0_neut_Jet_rawEnergy, "Jet_energyRing_dR0_neut_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR1_ch", &Jet_energyRing_dR1_ch, "Jet_energyRing_dR1_ch/F");
  t->Branch("Jet_energyRing_dR1_ch_Jet_rawEnergy", &Jet_energyRing_dR1_ch_Jet_rawEnergy, "Jet_energyRing_dR1_ch_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR1_em", &Jet_energyRing_dR1_em, "Jet_energyRing_dR1_em/F");
  t->Branch("Jet_energyRing_dR1_em_Jet_rawEnergy", &Jet_energyRing_dR1_em_Jet_rawEnergy, "Jet_energyRing_dR1_em_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR1_mu", &Jet_energyRing_dR1_mu, "Jet_energyRing_dR1_mu/F");
  t->Branch("Jet_energyRing_dR1_mu_Jet_rawEnergy", &Jet_energyRing_dR1_mu_Jet_rawEnergy, "Jet_energyRing_dR1_mu_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR1_neut", &Jet_energyRing_dR1_neut, "Jet_energyRing_dR1_neut/F");
  t->Branch("Jet_energyRing_dR1_neut_Jet_rawEnergy", &Jet_energyRing_dR1_neut_Jet_rawEnergy, "Jet_energyRing_dR1_neut_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR2_ch", &Jet_energyRing_dR2_ch, "Jet_energyRing_dR2_ch/F");
  t->Branch("Jet_energyRing_dR2_ch_Jet_rawEnergy", &Jet_energyRing_dR2_ch_Jet_rawEnergy, "Jet_energyRing_dR2_ch_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR2_em", &Jet_energyRing_dR2_em, "Jet_energyRing_dR2_em/F");
  t->Branch("Jet_energyRing_dR2_em_Jet_rawEnergy", &Jet_energyRing_dR2_em_Jet_rawEnergy, "Jet_energyRing_dR2_em_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR2_mu", &Jet_energyRing_dR2_mu, "Jet_energyRing_dR2_mu/F");
  t->Branch("Jet_energyRing_dR2_mu_Jet_rawEnergy", &Jet_energyRing_dR2_mu_Jet_rawEnergy, "Jet_energyRing_dR2_mu_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR2_neut", &Jet_energyRing_dR2_neut, "Jet_energyRing_dR2_neut/F");
  t->Branch("Jet_energyRing_dR2_neut_Jet_rawEnergy", &Jet_energyRing_dR2_neut_Jet_rawEnergy, "Jet_energyRing_dR2_neut_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR3_ch", &Jet_energyRing_dR3_ch, "Jet_energyRing_dR3_ch/F");
  t->Branch("Jet_energyRing_dR3_ch_Jet_rawEnergy", &Jet_energyRing_dR3_ch_Jet_rawEnergy, "Jet_energyRing_dR3_ch_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR3_em", &Jet_energyRing_dR3_em, "Jet_energyRing_dR3_em/F");
  t->Branch("Jet_energyRing_dR3_em_Jet_rawEnergy", &Jet_energyRing_dR3_em_Jet_rawEnergy, "Jet_energyRing_dR3_em_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR3_mu", &Jet_energyRing_dR3_mu, "Jet_energyRing_dR3_mu/F");
  t->Branch("Jet_energyRing_dR3_mu_Jet_rawEnergy", &Jet_energyRing_dR3_mu_Jet_rawEnergy, "Jet_energyRing_dR3_mu_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR3_neut", &Jet_energyRing_dR3_neut, "Jet_energyRing_dR3_neut/F");
  t->Branch("Jet_energyRing_dR3_neut_Jet_rawEnergy", &Jet_energyRing_dR3_neut_Jet_rawEnergy, "Jet_energyRing_dR3_neut_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR4_ch", &Jet_energyRing_dR4_ch, "Jet_energyRing_dR4_ch/F");
  t->Branch("Jet_energyRing_dR4_ch_Jet_rawEnergy", &Jet_energyRing_dR4_ch_Jet_rawEnergy, "Jet_energyRing_dR4_ch_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR4_em", &Jet_energyRing_dR4_em, "Jet_energyRing_dR4_em/F");
  t->Branch("Jet_energyRing_dR4_em_Jet_rawEnergy", &Jet_energyRing_dR4_em_Jet_rawEnergy, "Jet_energyRing_dR4_em_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR4_mu", &Jet_energyRing_dR4_mu, "Jet_energyRing_dR4_mu/F");
  t->Branch("Jet_energyRing_dR4_mu_Jet_rawEnergy", &Jet_energyRing_dR4_mu_Jet_rawEnergy, "Jet_energyRing_dR4_mu_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR4_neut", &Jet_energyRing_dR4_neut, "Jet_energyRing_dR4_neut/F");
  t->Branch("Jet_energyRing_dR4_neut_Jet_rawEnergy", &Jet_energyRing_dR4_neut_Jet_rawEnergy, "Jet_energyRing_dR4_neut_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR5_ch", &Jet_energyRing_dR5_ch, "Jet_energyRing_dR5_ch/F");
  t->Branch("Jet_energyRing_dR5_ch_Jet_rawEnergy", &Jet_energyRing_dR5_ch_Jet_rawEnergy, "Jet_energyRing_dR5_ch_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR5_em", &Jet_energyRing_dR5_em, "Jet_energyRing_dR5_em/F");
  t->Branch("Jet_energyRing_dR5_em_Jet_rawEnergy", &Jet_energyRing_dR5_em_Jet_rawEnergy, "Jet_energyRing_dR5_em_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR5_mu", &Jet_energyRing_dR5_mu, "Jet_energyRing_dR5_mu/F");
  t->Branch("Jet_energyRing_dR5_mu_Jet_rawEnergy", &Jet_energyRing_dR5_mu_Jet_rawEnergy, "Jet_energyRing_dR5_mu_Jet_rawEnergy/F");
  t->Branch("Jet_energyRing_dR5_neut", &Jet_energyRing_dR5_neut, "Jet_energyRing_dR5_neut/F");
  t->Branch("Jet_energyRing_dR5_neut_Jet_rawEnergy", &Jet_energyRing_dR5_neut_Jet_rawEnergy, "Jet_energyRing_dR5_neut_Jet_rawEnergy/F");
  t->Branch("Jet_eta", &Jet_eta, "Jet_eta/F");
  t->Branch("Jet_leadTrackPt", &Jet_leadTrackPt, "Jet_leadTrackPt/F");
  t->Branch("Jet_leptonDeltaR", &Jet_leptonDeltaR, "Jet_leptonDeltaR/F");
  t->Branch("Jet_leptonPdgId", &Jet_leptonPdgId, "Jet_leptonPdgId/I");
  t->Branch("Jet_leptonPt", &Jet_leptonPt, "Jet_leptonPt/F");
  t->Branch("Jet_leptonPtRel", &Jet_leptonPtRel, "Jet_leptonPtRel/F");
  t->Branch("Jet_leptonPtRelInv", &Jet_leptonPtRelInv, "Jet_leptonPtRelInv/F");
  t->Branch("Jet_mass", &Jet_mass, "Jet_mass/F");
  t->Branch("Jet_mcFlavour", &Jet_mcFlavour, "Jet_mcFlavour/F");
  t->Branch("Jet_mcPt", &Jet_mcPt, "Jet_mcPt/F");
  t->Branch("Jet_met_dPhi", &Jet_met_dPhi, "Jet_met_dPhi/F");
  t->Branch("Jet_mt", &Jet_mt, "Jet_mt/F");
  t->Branch("Jet_neEmEF", &Jet_neEmEF, "Jet_neEmEF/F");
  t->Branch("Jet_neHEF", &Jet_neHEF, "Jet_neHEF/F");
  t->Branch("Jet_numDaughters_pt03", &Jet_numDaughters_pt03, "Jet_numDaughters_pt03/s");
  t->Branch("Jet_numberOfDaughters", &Jet_numberOfDaughters, "Jet_numberOfDaughters/s");
  t->Branch("Jet_pf_0_deta", &Jet_pf_0_deta, "Jet_pf_0_deta/F");
  t->Branch("Jet_pf_0_dphi", &Jet_pf_0_dphi, "Jet_pf_0_dphi/F");
  t->Branch("Jet_pf_0_dxy", &Jet_pf_0_dxy, "Jet_pf_0_dxy/F");
  t->Branch("Jet_pf_0_dz", &Jet_pf_0_dz, "Jet_pf_0_dz/F");
  t->Branch("Jet_pf_0_pdgid", &Jet_pf_0_pdgid, "Jet_pf_0_pdgid/I");
  t->Branch("Jet_pf_0_ptfrac", &Jet_pf_0_ptfrac, "Jet_pf_0_ptfrac/F");
  t->Branch("Jet_pf_0_puppiwt", &Jet_pf_0_puppiwt, "Jet_pf_0_puppiwt/F");
  t->Branch("Jet_pf_1_deta", &Jet_pf_1_deta, "Jet_pf_1_deta/F");
  t->Branch("Jet_pf_1_dphi", &Jet_pf_1_dphi, "Jet_pf_1_dphi/F");
  t->Branch("Jet_pf_1_dxy", &Jet_pf_1_dxy, "Jet_pf_1_dxy/F");
  t->Branch("Jet_pf_1_dz", &Jet_pf_1_dz, "Jet_pf_1_dz/F");
  t->Branch("Jet_pf_1_pdgid", &Jet_pf_1_pdgid, "Jet_pf_1_pdgid/I");
  t->Branch("Jet_pf_1_ptfrac", &Jet_pf_1_ptfrac, "Jet_pf_1_ptfrac/F");
  t->Branch("Jet_pf_1_puppiwt", &Jet_pf_1_puppiwt, "Jet_pf_1_puppiwt/F");
  t->Branch("Jet_pf_2_deta", &Jet_pf_2_deta, "Jet_pf_2_deta/F");
  t->Branch("Jet_pf_2_dphi", &Jet_pf_2_dphi, "Jet_pf_2_dphi/F");
  t->Branch("Jet_pf_2_dxy", &Jet_pf_2_dxy, "Jet_pf_2_dxy/F");
  t->Branch("Jet_pf_2_dz", &Jet_pf_2_dz, "Jet_pf_2_dz/F");
  t->Branch("Jet_pf_2_pdgid", &Jet_pf_2_pdgid, "Jet_pf_2_pdgid/I");
  t->Branch("Jet_pf_2_ptfrac", &Jet_pf_2_ptfrac, "Jet_pf_2_ptfrac/F");
  t->Branch("Jet_pf_2_puppiwt", &Jet_pf_2_puppiwt, "Jet_pf_2_puppiwt/F");
  t->Branch("Jet_pf_3_deta", &Jet_pf_3_deta, "Jet_pf_3_deta/F");
  t->Branch("Jet_pf_3_dphi", &Jet_pf_3_dphi, "Jet_pf_3_dphi/F");
  t->Branch("Jet_pf_3_dxy", &Jet_pf_3_dxy, "Jet_pf_3_dxy/F");
  t->Branch("Jet_pf_3_dz", &Jet_pf_3_dz, "Jet_pf_3_dz/F");
  t->Branch("Jet_pf_3_pdgid", &Jet_pf_3_pdgid, "Jet_pf_3_pdgid/I");
  t->Branch("Jet_pf_3_ptfrac", &Jet_pf_3_ptfrac, "Jet_pf_3_ptfrac/F");
  t->Branch("Jet_pf_3_puppiwt", &Jet_pf_3_puppiwt, "Jet_pf_3_puppiwt/F");
  t->Branch("Jet_pf_4_deta", &Jet_pf_4_deta, "Jet_pf_4_deta/F");
  t->Branch("Jet_pf_4_dphi", &Jet_pf_4_dphi, "Jet_pf_4_dphi/F");
  t->Branch("Jet_pf_4_dxy", &Jet_pf_4_dxy, "Jet_pf_4_dxy/F");
  t->Branch("Jet_pf_4_dz", &Jet_pf_4_dz, "Jet_pf_4_dz/F");
  t->Branch("Jet_pf_4_pdgid", &Jet_pf_4_pdgid, "Jet_pf_4_pdgid/I");
  t->Branch("Jet_pf_4_ptfrac", &Jet_pf_4_ptfrac, "Jet_pf_4_ptfrac/F");
  t->Branch("Jet_pf_4_puppiwt", &Jet_pf_4_puppiwt, "Jet_pf_4_puppiwt/F");
  t->Branch("Jet_pf_5_deta", &Jet_pf_5_deta, "Jet_pf_5_deta/F");
  t->Branch("Jet_pf_5_dphi", &Jet_pf_5_dphi, "Jet_pf_5_dphi/F");
  t->Branch("Jet_pf_5_dxy", &Jet_pf_5_dxy, "Jet_pf_5_dxy/F");
  t->Branch("Jet_pf_5_dz", &Jet_pf_5_dz, "Jet_pf_5_dz/F");
  t->Branch("Jet_pf_5_pdgid", &Jet_pf_5_pdgid, "Jet_pf_5_pdgid/I");
  t->Branch("Jet_pf_5_ptfrac", &Jet_pf_5_ptfrac, "Jet_pf_5_ptfrac/F");
  t->Branch("Jet_pf_5_puppiwt", &Jet_pf_5_puppiwt, "Jet_pf_5_puppiwt/F");
  t->Branch("Jet_pf_6_deta", &Jet_pf_6_deta, "Jet_pf_6_deta/F");
  t->Branch("Jet_pf_6_dphi", &Jet_pf_6_dphi, "Jet_pf_6_dphi/F");
  t->Branch("Jet_pf_6_dxy", &Jet_pf_6_dxy, "Jet_pf_6_dxy/F");
  t->Branch("Jet_pf_6_dz", &Jet_pf_6_dz, "Jet_pf_6_dz/F");
  t->Branch("Jet_pf_6_pdgid", &Jet_pf_6_pdgid, "Jet_pf_6_pdgid/I");
  t->Branch("Jet_pf_6_ptfrac", &Jet_pf_6_ptfrac, "Jet_pf_6_ptfrac/F");
  t->Branch("Jet_pf_6_puppiwt", &Jet_pf_6_puppiwt, "Jet_pf_6_puppiwt/F");
  t->Branch("Jet_pf_7_deta", &Jet_pf_7_deta, "Jet_pf_7_deta/F");
  t->Branch("Jet_pf_7_dphi", &Jet_pf_7_dphi, "Jet_pf_7_dphi/F");
  t->Branch("Jet_pf_7_dxy", &Jet_pf_7_dxy, "Jet_pf_7_dxy/F");
  t->Branch("Jet_pf_7_dz", &Jet_pf_7_dz, "Jet_pf_7_dz/F");
  t->Branch("Jet_pf_7_pdgid", &Jet_pf_7_pdgid, "Jet_pf_7_pdgid/I");
  t->Branch("Jet_pf_7_ptfrac", &Jet_pf_7_ptfrac, "Jet_pf_7_ptfrac/F");
  t->Branch("Jet_pf_7_puppiwt", &Jet_pf_7_puppiwt, "Jet_pf_7_puppiwt/F");
  t->Branch("Jet_pf_8_deta", &Jet_pf_8_deta, "Jet_pf_8_deta/F");
  t->Branch("Jet_pf_8_dphi", &Jet_pf_8_dphi, "Jet_pf_8_dphi/F");
  t->Branch("Jet_pf_8_dxy", &Jet_pf_8_dxy, "Jet_pf_8_dxy/F");
  t->Branch("Jet_pf_8_dz", &Jet_pf_8_dz, "Jet_pf_8_dz/F");
  t->Branch("Jet_pf_8_pdgid", &Jet_pf_8_pdgid, "Jet_pf_8_pdgid/I");
  t->Branch("Jet_pf_8_ptfrac", &Jet_pf_8_ptfrac, "Jet_pf_8_ptfrac/F");
  t->Branch("Jet_pf_8_puppiwt", &Jet_pf_8_puppiwt, "Jet_pf_8_puppiwt/F");
  t->Branch("Jet_pf_9_deta", &Jet_pf_9_deta, "Jet_pf_9_deta/F");
  t->Branch("Jet_pf_9_dphi", &Jet_pf_9_dphi, "Jet_pf_9_dphi/F");
  t->Branch("Jet_pf_9_dxy", &Jet_pf_9_dxy, "Jet_pf_9_dxy/F");
  t->Branch("Jet_pf_9_dz", &Jet_pf_9_dz, "Jet_pf_9_dz/F");
  t->Branch("Jet_pf_9_pdgid", &Jet_pf_9_pdgid, "Jet_pf_9_pdgid/I");
  t->Branch("Jet_pf_9_ptfrac", &Jet_pf_9_ptfrac, "Jet_pf_9_ptfrac/F");
  t->Branch("Jet_pf_9_puppiwt", &Jet_pf_9_puppiwt, "Jet_pf_9_puppiwt/F");
  t->Branch("Jet_phi", &Jet_phi, "Jet_phi/F");
  t->Branch("Jet_pt", &Jet_pt, "Jet_pt/F");
  t->Branch("Jet_ptd", &Jet_ptd, "Jet_ptd/F");
  t->Branch("Jet_puId", &Jet_puId, "Jet_puId/F");
  t->Branch("Jet_raw", &Jet_raw, "Jet_raw/F");
  t->Branch("Jet_rawEnergy", &Jet_rawEnergy, "Jet_rawEnergy/F");
  t->Branch("Jet_rawFactor", &Jet_rawFactor, "Jet_rawFactor/F");
  t->Branch("Jet_tf_ptratio", &Jet_tf_ptratio, "Jet_tf_ptratio/F");
  t->Branch("Jet_tf_ptratio_nopf", &Jet_tf_ptratio_nopf, "Jet_tf_ptratio_nopf/F");
  t->Branch("Jet_vtx3dL", &Jet_vtx3dL, "Jet_vtx3dL/F");
  t->Branch("Jet_vtx3deL", &Jet_vtx3deL, "Jet_vtx3deL/F");
  t->Branch("Jet_vtxMass", &Jet_vtxMass, "Jet_vtxMass/F");
  t->Branch("Jet_vtxNtrk", &Jet_vtxNtrk, "Jet_vtxNtrk/s");
  t->Branch("Jet_vtxPt", &Jet_vtxPt, "Jet_vtxPt/F");
  t->Branch("Jet_withPtd", &Jet_withPtd, "Jet_withPtd/F");
  t->Branch("event", &event, "event/l");
  t->Branch("genWeight", &genWeight, "genWeight/F");
  t->Branch("isEle", &isEle, "isEle/F");
  t->Branch("isMu", &isMu, "isMu/F");
  t->Branch("isOther", &isOther, "isOther/F");
  t->Branch("luminosityBlock", &luminosityBlock, "luminosityBlock/l");
  t->Branch("met_phi", &met_phi, "met_phi/F");
  t->Branch("met_pt", &met_pt, "met_pt/F");
  t->Branch("nPVs", &nPVs, "nPVs/F");
  t->Branch("nPVs_good", &nPVs_good, "nPVs_good/F");
  t->Branch("rho", &rho, "rho/F");
  t->Branch("run", &run, "run/i");
  tensorflow::GraphDef v2018_dan_session_graph_def;
  check_tf(tensorflow::ReadBinaryProto(tensorflow::Env::Default(), "data/v2018_dan.pb", &v2018_dan_session_graph_def));
  check_tf(v2018_dan_session->Create(v2018_dan_session_graph_def));
  tensorflow::GraphDef v2018_dan_noPFs_session_graph_def;
  check_tf(tensorflow::ReadBinaryProto(tensorflow::Env::Default(), "data/v2018_dan_noPFs.pb", &v2018_dan_noPFs_session_graph_def));
  check_tf(v2018_dan_noPFs_session->Create(v2018_dan_noPFs_session_graph_def));
}

void regfile::reset(const panda::Event& e) {
  Jet_btagCMVA = 0;
  Jet_btagDeepB = 0;
  Jet_btagDeepC = 0;
  Jet_chEmEF = 0;
  Jet_chHEF = 0;
  Jet_e = 0;
  Jet_energyRing_dR0_ch = 0;
  Jet_energyRing_dR0_ch_Jet_rawEnergy = 0;
  Jet_energyRing_dR0_em = 0;
  Jet_energyRing_dR0_em_Jet_rawEnergy = 0;
  Jet_energyRing_dR0_mu = 0;
  Jet_energyRing_dR0_mu_Jet_rawEnergy = 0;
  Jet_energyRing_dR0_neut = 0;
  Jet_energyRing_dR0_neut_Jet_rawEnergy = 0;
  Jet_energyRing_dR1_ch = 0;
  Jet_energyRing_dR1_ch_Jet_rawEnergy = 0;
  Jet_energyRing_dR1_em = 0;
  Jet_energyRing_dR1_em_Jet_rawEnergy = 0;
  Jet_energyRing_dR1_mu = 0;
  Jet_energyRing_dR1_mu_Jet_rawEnergy = 0;
  Jet_energyRing_dR1_neut = 0;
  Jet_energyRing_dR1_neut_Jet_rawEnergy = 0;
  Jet_energyRing_dR2_ch = 0;
  Jet_energyRing_dR2_ch_Jet_rawEnergy = 0;
  Jet_energyRing_dR2_em = 0;
  Jet_energyRing_dR2_em_Jet_rawEnergy = 0;
  Jet_energyRing_dR2_mu = 0;
  Jet_energyRing_dR2_mu_Jet_rawEnergy = 0;
  Jet_energyRing_dR2_neut = 0;
  Jet_energyRing_dR2_neut_Jet_rawEnergy = 0;
  Jet_energyRing_dR3_ch = 0;
  Jet_energyRing_dR3_ch_Jet_rawEnergy = 0;
  Jet_energyRing_dR3_em = 0;
  Jet_energyRing_dR3_em_Jet_rawEnergy = 0;
  Jet_energyRing_dR3_mu = 0;
  Jet_energyRing_dR3_mu_Jet_rawEnergy = 0;
  Jet_energyRing_dR3_neut = 0;
  Jet_energyRing_dR3_neut_Jet_rawEnergy = 0;
  Jet_energyRing_dR4_ch = 0;
  Jet_energyRing_dR4_ch_Jet_rawEnergy = 0;
  Jet_energyRing_dR4_em = 0;
  Jet_energyRing_dR4_em_Jet_rawEnergy = 0;
  Jet_energyRing_dR4_mu = 0;
  Jet_energyRing_dR4_mu_Jet_rawEnergy = 0;
  Jet_energyRing_dR4_neut = 0;
  Jet_energyRing_dR4_neut_Jet_rawEnergy = 0;
  Jet_energyRing_dR5_ch = 0;
  Jet_energyRing_dR5_ch_Jet_rawEnergy = 0;
  Jet_energyRing_dR5_em = 0;
  Jet_energyRing_dR5_em_Jet_rawEnergy = 0;
  Jet_energyRing_dR5_mu = 0;
  Jet_energyRing_dR5_mu_Jet_rawEnergy = 0;
  Jet_energyRing_dR5_neut = 0;
  Jet_energyRing_dR5_neut_Jet_rawEnergy = 0;
  Jet_eta = 0;
  Jet_leadTrackPt = 0;
  Jet_leptonDeltaR = 0;
  Jet_leptonPdgId = 0;
  Jet_leptonPt = 0;
  Jet_leptonPtRel = 0;
  Jet_leptonPtRelInv = 0;
  Jet_mass = 0;
  Jet_mcFlavour = 0;
  Jet_mcPt = 0;
  Jet_met_dPhi = 0;
  Jet_mt = 0;
  Jet_neEmEF = 0;
  Jet_neHEF = 0;
  Jet_numDaughters_pt03 = 0;
  Jet_numberOfDaughters = 0;
  Jet_pf_0_deta = 0;
  Jet_pf_0_dphi = 0;
  Jet_pf_0_dxy = 0;
  Jet_pf_0_dz = 0;
  Jet_pf_0_pdgid = 0;
  Jet_pf_0_ptfrac = 0;
  Jet_pf_0_puppiwt = 0;
  Jet_pf_1_deta = 0;
  Jet_pf_1_dphi = 0;
  Jet_pf_1_dxy = 0;
  Jet_pf_1_dz = 0;
  Jet_pf_1_pdgid = 0;
  Jet_pf_1_ptfrac = 0;
  Jet_pf_1_puppiwt = 0;
  Jet_pf_2_deta = 0;
  Jet_pf_2_dphi = 0;
  Jet_pf_2_dxy = 0;
  Jet_pf_2_dz = 0;
  Jet_pf_2_pdgid = 0;
  Jet_pf_2_ptfrac = 0;
  Jet_pf_2_puppiwt = 0;
  Jet_pf_3_deta = 0;
  Jet_pf_3_dphi = 0;
  Jet_pf_3_dxy = 0;
  Jet_pf_3_dz = 0;
  Jet_pf_3_pdgid = 0;
  Jet_pf_3_ptfrac = 0;
  Jet_pf_3_puppiwt = 0;
  Jet_pf_4_deta = 0;
  Jet_pf_4_dphi = 0;
  Jet_pf_4_dxy = 0;
  Jet_pf_4_dz = 0;
  Jet_pf_4_pdgid = 0;
  Jet_pf_4_ptfrac = 0;
  Jet_pf_4_puppiwt = 0;
  Jet_pf_5_deta = 0;
  Jet_pf_5_dphi = 0;
  Jet_pf_5_dxy = 0;
  Jet_pf_5_dz = 0;
  Jet_pf_5_pdgid = 0;
  Jet_pf_5_ptfrac = 0;
  Jet_pf_5_puppiwt = 0;
  Jet_pf_6_deta = 0;
  Jet_pf_6_dphi = 0;
  Jet_pf_6_dxy = 0;
  Jet_pf_6_dz = 0;
  Jet_pf_6_pdgid = 0;
  Jet_pf_6_ptfrac = 0;
  Jet_pf_6_puppiwt = 0;
  Jet_pf_7_deta = 0;
  Jet_pf_7_dphi = 0;
  Jet_pf_7_dxy = 0;
  Jet_pf_7_dz = 0;
  Jet_pf_7_pdgid = 0;
  Jet_pf_7_ptfrac = 0;
  Jet_pf_7_puppiwt = 0;
  Jet_pf_8_deta = 0;
  Jet_pf_8_dphi = 0;
  Jet_pf_8_dxy = 0;
  Jet_pf_8_dz = 0;
  Jet_pf_8_pdgid = 0;
  Jet_pf_8_ptfrac = 0;
  Jet_pf_8_puppiwt = 0;
  Jet_pf_9_deta = 0;
  Jet_pf_9_dphi = 0;
  Jet_pf_9_dxy = 0;
  Jet_pf_9_dz = 0;
  Jet_pf_9_pdgid = 0;
  Jet_pf_9_ptfrac = 0;
  Jet_pf_9_puppiwt = 0;
  Jet_phi = 0;
  Jet_pt = 0;
  Jet_ptd = 0;
  Jet_puId = 0;
  Jet_raw = 0;
  Jet_rawEnergy = 0;
  Jet_rawFactor = 0;
  Jet_tf_ptratio = 0;
  Jet_tf_ptratio_nopf = 0;
  Jet_vtx3dL = 0;
  Jet_vtx3deL = 0;
  Jet_vtxMass = 0;
  Jet_vtxNtrk = 0;
  Jet_vtxPt = 0;
  Jet_withPtd = 0;
  event = e.eventNumber;
  genWeight = e.weight;
  isEle = 0;
  isMu = 0;
  isOther = 0;
  luminosityBlock = e.lumiNumber;
  met_phi = e.pfMet.phi;
  met_pt = e.pfMet.pt;
  nPVs = e.npvTrue;
  nPVs_good = e.npv;
  rho = e.rho;
  run = e.runNumber;
}

void regfile::fill() {
  isEle = std::abs(Jet_leptonPdgId) == 11;
  isMu = std::abs(Jet_leptonPdgId) == 13;
  isOther = not (isEle or isMu);
  Jet_withPtd = Jet_ptd;
  Jet_met_dPhi = TVector2::Phi_mpi_pi(met_phi - Jet_phi);
  std::vector<std::pair<std::string, tensorflow::Tensor>> v2018_dan_session_inputs {{"input", {tensorflow::DT_FLOAT, {1, 78}}}};
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 0) = static_cast<float>(Jet_chEmEF);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 1) = static_cast<float>(Jet_chHEF);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 2) = static_cast<float>(Jet_energyRing_dR0_ch_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 3) = static_cast<float>(Jet_energyRing_dR0_em_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 4) = static_cast<float>(Jet_energyRing_dR0_mu_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 5) = static_cast<float>(Jet_energyRing_dR0_neut_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 6) = static_cast<float>(Jet_energyRing_dR1_ch_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 7) = static_cast<float>(Jet_energyRing_dR1_em_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 8) = static_cast<float>(Jet_energyRing_dR1_mu_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 9) = static_cast<float>(Jet_energyRing_dR1_neut_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 10) = static_cast<float>(Jet_energyRing_dR2_ch_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 11) = static_cast<float>(Jet_energyRing_dR2_em_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 12) = static_cast<float>(Jet_energyRing_dR2_mu_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 13) = static_cast<float>(Jet_energyRing_dR2_neut_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 14) = static_cast<float>(Jet_energyRing_dR3_ch_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 15) = static_cast<float>(Jet_energyRing_dR3_em_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 16) = static_cast<float>(Jet_energyRing_dR3_mu_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 17) = static_cast<float>(Jet_energyRing_dR3_neut_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 18) = static_cast<float>(Jet_energyRing_dR4_ch_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 19) = static_cast<float>(Jet_energyRing_dR4_em_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 20) = static_cast<float>(Jet_energyRing_dR4_mu_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 21) = static_cast<float>(Jet_energyRing_dR4_neut_Jet_rawEnergy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 22) = static_cast<float>(Jet_eta);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 23) = static_cast<float>(Jet_leadTrackPt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 24) = static_cast<float>(Jet_leptonDeltaR);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 25) = static_cast<float>(Jet_leptonPtRel);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 26) = static_cast<float>(Jet_leptonPtRelInv);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 27) = static_cast<float>(Jet_mass);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 28) = static_cast<float>(Jet_mt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 29) = static_cast<float>(Jet_neEmEF);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 30) = static_cast<float>(Jet_neHEF);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 31) = static_cast<float>(Jet_numDaughters_pt03);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 32) = static_cast<float>(Jet_pt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 33) = static_cast<float>(Jet_ptd);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 34) = static_cast<float>(Jet_vtx3dL);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 35) = static_cast<float>(Jet_vtx3deL);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 36) = static_cast<float>(Jet_vtxMass);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 37) = static_cast<float>(Jet_vtxNtrk);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 38) = static_cast<float>(Jet_vtxPt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 39) = static_cast<float>(isEle);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 40) = static_cast<float>(isMu);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 41) = static_cast<float>(isOther);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 42) = static_cast<float>(rho);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 43) = static_cast<float>(Jet_pf_0_deta);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 44) = static_cast<float>(Jet_pf_0_dphi);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 45) = static_cast<float>(Jet_pf_0_dxy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 46) = static_cast<float>(Jet_pf_0_dz);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 47) = static_cast<float>(Jet_pf_0_pdgid);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 48) = static_cast<float>(Jet_pf_0_ptfrac);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 49) = static_cast<float>(Jet_pf_0_puppiwt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 50) = static_cast<float>(Jet_pf_1_deta);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 51) = static_cast<float>(Jet_pf_1_dphi);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 52) = static_cast<float>(Jet_pf_1_dxy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 53) = static_cast<float>(Jet_pf_1_dz);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 54) = static_cast<float>(Jet_pf_1_pdgid);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 55) = static_cast<float>(Jet_pf_1_ptfrac);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 56) = static_cast<float>(Jet_pf_1_puppiwt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 57) = static_cast<float>(Jet_pf_2_deta);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 58) = static_cast<float>(Jet_pf_2_dphi);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 59) = static_cast<float>(Jet_pf_2_dxy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 60) = static_cast<float>(Jet_pf_2_dz);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 61) = static_cast<float>(Jet_pf_2_pdgid);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 62) = static_cast<float>(Jet_pf_2_ptfrac);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 63) = static_cast<float>(Jet_pf_2_puppiwt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 64) = static_cast<float>(Jet_pf_3_deta);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 65) = static_cast<float>(Jet_pf_3_dphi);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 66) = static_cast<float>(Jet_pf_3_dxy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 67) = static_cast<float>(Jet_pf_3_dz);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 68) = static_cast<float>(Jet_pf_3_pdgid);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 69) = static_cast<float>(Jet_pf_3_ptfrac);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 70) = static_cast<float>(Jet_pf_3_puppiwt);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 71) = static_cast<float>(Jet_pf_4_deta);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 72) = static_cast<float>(Jet_pf_4_dphi);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 73) = static_cast<float>(Jet_pf_4_dxy);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 74) = static_cast<float>(Jet_pf_4_dz);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 75) = static_cast<float>(Jet_pf_4_pdgid);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 76) = static_cast<float>(Jet_pf_4_ptfrac);
  v2018_dan_session_inputs[0].second.matrix<float>()(0, 77) = static_cast<float>(Jet_pf_4_puppiwt);
  std::vector<tensorflow::Tensor> v2018_dan_session_outputs_Jet;
  check_tf(v2018_dan_session->Run(v2018_dan_session_inputs, {"output_0/BiasAdd"}, {}, &v2018_dan_session_outputs_Jet));
  Jet_tf_ptratio = v2018_dan_session_outputs_Jet[0].matrix<float>()(0, 0);
  std::vector<std::pair<std::string, tensorflow::Tensor>> v2018_dan_noPFs_session_inputs {{"input", {tensorflow::DT_FLOAT, {1, 43}}}};
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 0) = static_cast<float>(Jet_chEmEF);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 1) = static_cast<float>(Jet_chHEF);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 2) = static_cast<float>(Jet_energyRing_dR0_ch_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 3) = static_cast<float>(Jet_energyRing_dR0_em_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 4) = static_cast<float>(Jet_energyRing_dR0_mu_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 5) = static_cast<float>(Jet_energyRing_dR0_neut_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 6) = static_cast<float>(Jet_energyRing_dR1_ch_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 7) = static_cast<float>(Jet_energyRing_dR1_em_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 8) = static_cast<float>(Jet_energyRing_dR1_mu_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 9) = static_cast<float>(Jet_energyRing_dR1_neut_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 10) = static_cast<float>(Jet_energyRing_dR2_ch_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 11) = static_cast<float>(Jet_energyRing_dR2_em_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 12) = static_cast<float>(Jet_energyRing_dR2_mu_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 13) = static_cast<float>(Jet_energyRing_dR2_neut_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 14) = static_cast<float>(Jet_energyRing_dR3_ch_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 15) = static_cast<float>(Jet_energyRing_dR3_em_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 16) = static_cast<float>(Jet_energyRing_dR3_mu_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 17) = static_cast<float>(Jet_energyRing_dR3_neut_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 18) = static_cast<float>(Jet_energyRing_dR4_ch_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 19) = static_cast<float>(Jet_energyRing_dR4_em_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 20) = static_cast<float>(Jet_energyRing_dR4_mu_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 21) = static_cast<float>(Jet_energyRing_dR4_neut_Jet_rawEnergy);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 22) = static_cast<float>(Jet_eta);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 23) = static_cast<float>(Jet_leadTrackPt);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 24) = static_cast<float>(Jet_leptonDeltaR);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 25) = static_cast<float>(Jet_leptonPtRel);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 26) = static_cast<float>(Jet_leptonPtRelInv);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 27) = static_cast<float>(Jet_mass);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 28) = static_cast<float>(Jet_mt);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 29) = static_cast<float>(Jet_neEmEF);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 30) = static_cast<float>(Jet_neHEF);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 31) = static_cast<float>(Jet_numDaughters_pt03);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 32) = static_cast<float>(Jet_pt);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 33) = static_cast<float>(Jet_ptd);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 34) = static_cast<float>(Jet_vtx3dL);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 35) = static_cast<float>(Jet_vtx3deL);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 36) = static_cast<float>(Jet_vtxMass);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 37) = static_cast<float>(Jet_vtxNtrk);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 38) = static_cast<float>(Jet_vtxPt);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 39) = static_cast<float>(isEle);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 40) = static_cast<float>(isMu);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 41) = static_cast<float>(isOther);
  v2018_dan_noPFs_session_inputs[0].second.matrix<float>()(0, 42) = static_cast<float>(rho);
  std::vector<tensorflow::Tensor> v2018_dan_noPFs_session_outputs_Jet;
  check_tf(v2018_dan_noPFs_session->Run(v2018_dan_noPFs_session_inputs, {"output_0/BiasAdd"}, {}, &v2018_dan_noPFs_session_outputs_Jet));
  Jet_tf_ptratio_nopf = v2018_dan_noPFs_session_outputs_Jet[0].matrix<float>()(0, 0);
  t->Fill();
}

template <typename G> void regfile::set_jet(const jet base, const panda::Jet& jet, const gennujet::GenNuVec& withnu, const G gen) {
  auto p4 = jet.p4();
  auto info = regression::GetJetInfo(jet);
  switch(base) {
  case regfile::jet::Jet:
    Jet_puId = jet.puid;
    Jet_btagCMVA = jet.cmva;
    Jet_btagDeepC = jet.deepCSVc + jet.deepCSVcc;
    Jet_btagDeepB = jet.deepCSVb + jet.deepCSVbb;
    Jet_raw = jet.rawPt/jet.pt();
    Jet_pt = p4.Pt();
    Jet_eta = p4.Eta();
    Jet_phi = p4.Phi();
    Jet_mt = p4.Mt();
    Jet_e = p4.E();
    Jet_mass = p4.M();
    Jet_chHEF = jet.chf;
    Jet_neHEF = jet.nhf;
    Jet_chEmEF = jet.cef;
    Jet_neEmEF = jet.nef;
    Jet_vtxNtrk = info.vtxNtrk;
    Jet_vtxMass = info.vtxMass;
    Jet_vtx3dL = info.vtx3dL;
    Jet_vtx3deL = info.vtx3deL;
    Jet_vtxPt = info.vtxPt;
    Jet_leadTrackPt = info.maxpfpt;
    Jet_rawFactor = 1 - jet.rawPt/Jet_pt;
    Jet_rawEnergy = Jet_e * jet.rawPt/Jet_pt;
    Jet_mcPt = withnu.genvec.Pt();
    Jet_mcFlavour = gen->partonFlavor;
    Jet_leptonPdgId = info.leptonPdgId;
    Jet_leptonPt = info.leptonPt;
    Jet_leptonPtRel = info.leptonPtRel;
    Jet_leptonPtRelInv = info.leptonPtRelInv;
    Jet_leptonDeltaR = info.leptonDeltaR;
    Jet_ptd = info.ptD;
    Jet_energyRing_dR0_neut = info.neut_rings[0].first;
    Jet_energyRing_dR1_neut = info.neut_rings[1].first;
    Jet_energyRing_dR2_neut = info.neut_rings[2].first;
    Jet_energyRing_dR3_neut = info.neut_rings[3].first;
    Jet_energyRing_dR4_neut = info.neut_rings[4].first;
    Jet_energyRing_dR5_neut = info.neut_rings[5].first;
    Jet_energyRing_dR0_ch = info.ch_rings[0].first;
    Jet_energyRing_dR1_ch = info.ch_rings[1].first;
    Jet_energyRing_dR2_ch = info.ch_rings[2].first;
    Jet_energyRing_dR3_ch = info.ch_rings[3].first;
    Jet_energyRing_dR4_ch = info.ch_rings[4].first;
    Jet_energyRing_dR5_ch = info.ch_rings[5].first;
    Jet_energyRing_dR0_em = info.em_rings[0].first;
    Jet_energyRing_dR1_em = info.em_rings[1].first;
    Jet_energyRing_dR2_em = info.em_rings[2].first;
    Jet_energyRing_dR3_em = info.em_rings[3].first;
    Jet_energyRing_dR4_em = info.em_rings[4].first;
    Jet_energyRing_dR5_em = info.em_rings[5].first;
    Jet_energyRing_dR0_mu = info.mu_rings[0].first;
    Jet_energyRing_dR1_mu = info.mu_rings[1].first;
    Jet_energyRing_dR2_mu = info.mu_rings[2].first;
    Jet_energyRing_dR3_mu = info.mu_rings[3].first;
    Jet_energyRing_dR4_mu = info.mu_rings[4].first;
    Jet_energyRing_dR5_mu = info.mu_rings[5].first;
    Jet_energyRing_dR0_neut_Jet_rawEnergy = Jet_energyRing_dR0_neut/Jet_rawEnergy;
    Jet_energyRing_dR1_neut_Jet_rawEnergy = Jet_energyRing_dR1_neut/Jet_rawEnergy;
    Jet_energyRing_dR2_neut_Jet_rawEnergy = Jet_energyRing_dR2_neut/Jet_rawEnergy;
    Jet_energyRing_dR3_neut_Jet_rawEnergy = Jet_energyRing_dR3_neut/Jet_rawEnergy;
    Jet_energyRing_dR4_neut_Jet_rawEnergy = Jet_energyRing_dR4_neut/Jet_rawEnergy;
    Jet_energyRing_dR5_neut_Jet_rawEnergy = Jet_energyRing_dR5_neut/Jet_rawEnergy;
    Jet_energyRing_dR0_ch_Jet_rawEnergy = Jet_energyRing_dR0_ch/Jet_rawEnergy;
    Jet_energyRing_dR1_ch_Jet_rawEnergy = Jet_energyRing_dR1_ch/Jet_rawEnergy;
    Jet_energyRing_dR2_ch_Jet_rawEnergy = Jet_energyRing_dR2_ch/Jet_rawEnergy;
    Jet_energyRing_dR3_ch_Jet_rawEnergy = Jet_energyRing_dR3_ch/Jet_rawEnergy;
    Jet_energyRing_dR4_ch_Jet_rawEnergy = Jet_energyRing_dR4_ch/Jet_rawEnergy;
    Jet_energyRing_dR5_ch_Jet_rawEnergy = Jet_energyRing_dR5_ch/Jet_rawEnergy;
    Jet_energyRing_dR0_em_Jet_rawEnergy = Jet_energyRing_dR0_em/Jet_rawEnergy;
    Jet_energyRing_dR1_em_Jet_rawEnergy = Jet_energyRing_dR1_em/Jet_rawEnergy;
    Jet_energyRing_dR2_em_Jet_rawEnergy = Jet_energyRing_dR2_em/Jet_rawEnergy;
    Jet_energyRing_dR3_em_Jet_rawEnergy = Jet_energyRing_dR3_em/Jet_rawEnergy;
    Jet_energyRing_dR4_em_Jet_rawEnergy = Jet_energyRing_dR4_em/Jet_rawEnergy;
    Jet_energyRing_dR5_em_Jet_rawEnergy = Jet_energyRing_dR5_em/Jet_rawEnergy;
    Jet_energyRing_dR0_mu_Jet_rawEnergy = Jet_energyRing_dR0_mu/Jet_rawEnergy;
    Jet_energyRing_dR1_mu_Jet_rawEnergy = Jet_energyRing_dR1_mu/Jet_rawEnergy;
    Jet_energyRing_dR2_mu_Jet_rawEnergy = Jet_energyRing_dR2_mu/Jet_rawEnergy;
    Jet_energyRing_dR3_mu_Jet_rawEnergy = Jet_energyRing_dR3_mu/Jet_rawEnergy;
    Jet_energyRing_dR4_mu_Jet_rawEnergy = Jet_energyRing_dR4_mu/Jet_rawEnergy;
    Jet_energyRing_dR5_mu_Jet_rawEnergy = Jet_energyRing_dR5_mu/Jet_rawEnergy;
    Jet_numDaughters_pt03 = info.num03;
    Jet_numberOfDaughters = jet.constituents.size();
    Jet_pf_0_ptfrac = info.pfinfo[0].ptfrac;
    Jet_pf_1_ptfrac = info.pfinfo[1].ptfrac;
    Jet_pf_2_ptfrac = info.pfinfo[2].ptfrac;
    Jet_pf_3_ptfrac = info.pfinfo[3].ptfrac;
    Jet_pf_4_ptfrac = info.pfinfo[4].ptfrac;
    Jet_pf_5_ptfrac = info.pfinfo[5].ptfrac;
    Jet_pf_6_ptfrac = info.pfinfo[6].ptfrac;
    Jet_pf_7_ptfrac = info.pfinfo[7].ptfrac;
    Jet_pf_8_ptfrac = info.pfinfo[8].ptfrac;
    Jet_pf_9_ptfrac = info.pfinfo[9].ptfrac;
    Jet_pf_0_deta = info.pfinfo[0].deta;
    Jet_pf_1_deta = info.pfinfo[1].deta;
    Jet_pf_2_deta = info.pfinfo[2].deta;
    Jet_pf_3_deta = info.pfinfo[3].deta;
    Jet_pf_4_deta = info.pfinfo[4].deta;
    Jet_pf_5_deta = info.pfinfo[5].deta;
    Jet_pf_6_deta = info.pfinfo[6].deta;
    Jet_pf_7_deta = info.pfinfo[7].deta;
    Jet_pf_8_deta = info.pfinfo[8].deta;
    Jet_pf_9_deta = info.pfinfo[9].deta;
    Jet_pf_0_dphi = info.pfinfo[0].dphi;
    Jet_pf_1_dphi = info.pfinfo[1].dphi;
    Jet_pf_2_dphi = info.pfinfo[2].dphi;
    Jet_pf_3_dphi = info.pfinfo[3].dphi;
    Jet_pf_4_dphi = info.pfinfo[4].dphi;
    Jet_pf_5_dphi = info.pfinfo[5].dphi;
    Jet_pf_6_dphi = info.pfinfo[6].dphi;
    Jet_pf_7_dphi = info.pfinfo[7].dphi;
    Jet_pf_8_dphi = info.pfinfo[8].dphi;
    Jet_pf_9_dphi = info.pfinfo[9].dphi;
    Jet_pf_0_puppiwt = info.pfinfo[0].puppiwt;
    Jet_pf_1_puppiwt = info.pfinfo[1].puppiwt;
    Jet_pf_2_puppiwt = info.pfinfo[2].puppiwt;
    Jet_pf_3_puppiwt = info.pfinfo[3].puppiwt;
    Jet_pf_4_puppiwt = info.pfinfo[4].puppiwt;
    Jet_pf_5_puppiwt = info.pfinfo[5].puppiwt;
    Jet_pf_6_puppiwt = info.pfinfo[6].puppiwt;
    Jet_pf_7_puppiwt = info.pfinfo[7].puppiwt;
    Jet_pf_8_puppiwt = info.pfinfo[8].puppiwt;
    Jet_pf_9_puppiwt = info.pfinfo[9].puppiwt;
    Jet_pf_0_dxy = info.pfinfo[0].dxy;
    Jet_pf_1_dxy = info.pfinfo[1].dxy;
    Jet_pf_2_dxy = info.pfinfo[2].dxy;
    Jet_pf_3_dxy = info.pfinfo[3].dxy;
    Jet_pf_4_dxy = info.pfinfo[4].dxy;
    Jet_pf_5_dxy = info.pfinfo[5].dxy;
    Jet_pf_6_dxy = info.pfinfo[6].dxy;
    Jet_pf_7_dxy = info.pfinfo[7].dxy;
    Jet_pf_8_dxy = info.pfinfo[8].dxy;
    Jet_pf_9_dxy = info.pfinfo[9].dxy;
    Jet_pf_0_dz = info.pfinfo[0].dz;
    Jet_pf_1_dz = info.pfinfo[1].dz;
    Jet_pf_2_dz = info.pfinfo[2].dz;
    Jet_pf_3_dz = info.pfinfo[3].dz;
    Jet_pf_4_dz = info.pfinfo[4].dz;
    Jet_pf_5_dz = info.pfinfo[5].dz;
    Jet_pf_6_dz = info.pfinfo[6].dz;
    Jet_pf_7_dz = info.pfinfo[7].dz;
    Jet_pf_8_dz = info.pfinfo[8].dz;
    Jet_pf_9_dz = info.pfinfo[9].dz;
    Jet_pf_0_pdgid = info.pfinfo[0].pdgid;
    Jet_pf_1_pdgid = info.pfinfo[1].pdgid;
    Jet_pf_2_pdgid = info.pfinfo[2].pdgid;
    Jet_pf_3_pdgid = info.pfinfo[3].pdgid;
    Jet_pf_4_pdgid = info.pfinfo[4].pdgid;
    Jet_pf_5_pdgid = info.pfinfo[5].pdgid;
    Jet_pf_6_pdgid = info.pfinfo[6].pdgid;
    Jet_pf_7_pdgid = info.pfinfo[7].pdgid;
    Jet_pf_8_pdgid = info.pfinfo[8].pdgid;
    Jet_pf_9_pdgid = info.pfinfo[9].pdgid;
    break;
  default:
    throw;
  }
}

#endif
